// ============================================================
// FINISH OPTIONS — Material/finish selections per trade
// Extracted from intake.jsx lines 305-325
// ============================================================

export const FINISH_OPTIONS: Record<string, string[]> = {
  roofing: ["Asphalt Shingles", "Concrete Tile", "Clay Tile", "Standing Seam Metal", "Flat Roof (TPO/Modified Bitumen)", "Synthetic Slate", "Wood Shake"],
  flooring: ["Engineered Hardwood", "LVP (Luxury Vinyl Plank)", "Laminate", "Porcelain Tile", "Ceramic Tile", "Natural Stone Tile", "Restore Existing Hardwood", "Polished Concrete", "Carpet"],
  countertops: ["Prefabricated Quartz", "Quartz", "Granite", "Marble", "Butcher Block", "Laminate", "Solid Surface (Corian)", "Concrete", "Porcelain Slab"],
  cabinets: ["Prefabricated Cabinets", "Custom Cabinets", "Semi-Custom Cabinets", "Stock Cabinets", "Reface Existing Cabinets", "Paint Existing Cabinets"],
  siding: ["Stucco", "Smooth Stucco", "Hardie Board (Fiber Cement)", "Wood Siding", "Vinyl Siding", "Board & Batten", "Stone Veneer", "Brick Veneer"],
  windows: ["Vinyl Windows", "Aluminum Windows", "Wood-Clad Windows", "Fiberglass Windows"],
  doors: ["Solid Core Interior", "Hollow Core Interior", "Fiberglass Entry", "Wood Entry", "Steel Entry", "Sliding Glass", "French Doors", "Barn Door"],
  paint_finish: ["Flat/Matte", "Eggshell", "Satin", "Semi-Gloss", "High Gloss"],
  foundation: ["Raised Foundation (Cripple Wall)", "Slab on Grade", "Pier & Beam"],
  tub_shower: ["Tub/Shower Combo", "Walk-In Shower", "Freestanding Tub", "Alcove Tub", "Walk-In Tub", "Shower Pan (Tile-Ready)", "Prefab Shower Base"],
  deck: ["Composite Decking (Trex/TimberTech)", "Pressure-Treated Wood", "Redwood", "Cedar", "PVC Decking", "Ipe Hardwood"],
  mini_split: ["Wall-Mounted Mini Split", "Ceiling Cassette", "Floor-Mounted", "Ducted Mini Split", "Multi-Zone System", "Central HVAC"],
  insulation_type: ["Batt (Fiberglass)", "Batt (Mineral Wool/Rockwool)", "Blown-In Cellulose", "Blown-In Fiberglass", "Spray Foam (Open Cell)", "Spray Foam (Closed Cell)", "Rigid Board Foam", "Radiant Barrier"],
  drywall_level: ["Level 3 \u2014 Tape & Coat (for tile/texture)", "Level 4 \u2014 Standard Finish (paint-ready)", "Level 5 \u2014 Skim Coat (smooth/high-end)"],
  drywall_texture: ["Smooth (No Texture)", "Knockdown", "Orange Peel", "Skip Trowel", "Hand Texture", "Match Existing"],
  specialty_paint: ["Standard Interior Paint (Default)", "Limewash", "Venetian Plaster", "Roman Clay", "Microcement", "Suede/Faux Finish", "Chalk Paint", "Cabinet Lacquer"],
  backsplash: ["Tile", "Ceramic Tile", "Porcelain Tile", "Glass Tile", "Natural Stone Tile", "Mosaic Tile", "Prefabricated Quartz Slab", "Full Slab (Marble/Quartz/Granite)", "Stainless Steel", "Brick Veneer"],
  layout_change: ["No Layout Change \u2014 Same Footprint", "Minor Layout Change \u2014 Fixtures Stay", "Major Layout Change \u2014 Rerouting Plumbing/Fixtures"],
  vanity: ["Prefabricated Vanity", "Custom Vanity", "Floating Vanity", "Freestanding Vanity", "Double Vanity"],
} as const;

// ============================================================
// ALT_DESCRIPTIONS — Detailed finish-specific descriptions
// Extracted from intake.jsx lines 327-404
// ============================================================

export const ALT_DESCRIPTIONS: Record<string, Record<string, string>> = {
  flooring: {
    "Restore Existing Hardwood": "Inspect and assess condition of existing hardwood floors \u2014 identify damage, wear, stains, and gaps.\nSand all hardwood surfaces using progressive grits (36, 60, 80, 100, 120) to remove old finish and level the surface.\nFill gaps, cracks, and nail holes with matching wood filler.\nRepair or replace damaged boards as needed \u2014 weave in new boards to match existing species and grain.\nApply wood stain if specified by client \u2014 allow for sample approval before full application.\nApply 3 coats of polyurethane finish (water-based or oil-based per client preference).\nLight sand between coats for proper adhesion.\nProtect finished floors during remaining construction phases.\nAllow proper cure time before furniture placement (48\u201372 hours).",
    "Polished Concrete": "Prep existing concrete slab \u2014 fill cracks, voids, and patch damaged areas.\nGrind concrete surface using progressive diamond grits (30, 50, 100, 200, 400, 800, 1500, 3000).\nApply densifier/hardener to strengthen the concrete surface.\nPolish to specified sheen level \u2014 matte, satin, or high-gloss per client selection.\nApply concrete stain or dye if specified by client for color.\nSeal with penetrating or topical sealer for stain resistance.\nInstall baseboards and transition strips at all material changes.",
    "Carpet": "Remove existing flooring and prep subfloor for carpet installation.\nInstall tack strips around perimeter of all carpeted areas.\nInstall carpet pad \u2014 density and thickness per client selection.\nStretch and install carpet throughout specified areas.\nSeam all joins using hot-melt seaming tape for invisible connections.\nInstall transition strips at all doorways and material changes.",
    "Engineered Hardwood": "Remove existing flooring and prep subfloor \u2014 level, clean, and install moisture barrier.\nAcclimate engineered hardwood on site per manufacturer requirements (48\u201372 hours).\nInstall engineered hardwood flooring \u2014 float, glue-down, or nail-down method per manufacturer specs.\nStagger joints properly and maintain expansion gaps at all walls.\nInstall baseboards, shoe molding, and transition strips at all thresholds and material changes.",
    "LVP (Luxury Vinyl Plank)": "Remove existing flooring and prep subfloor \u2014 level and clean.\nInstall moisture barrier underlayment if required.\nInstall luxury vinyl plank flooring throughout specified areas \u2014 click-lock or glue-down per product specs.\nMaintain expansion gaps at all walls and fixed objects.\nInstall baseboards, shoe molding, and transition strips at all doorways and material changes.",
    "Porcelain Tile": "Remove existing flooring and prep subfloor \u2014 level with self-leveling compound if needed.\nInstall cement board or Ditra membrane underlayment for tile.\nLay out tile pattern per client selection \u2014 straight, diagonal, herringbone, or other.\nInstall porcelain tile with proper thinset and spacers.\nGrout all joints with specified grout color and type.\nSeal grout lines and install baseboards and transition strips.",
    "Ceramic Tile": "Remove existing flooring and prep subfloor \u2014 level with self-leveling compound if needed.\nInstall cement board or Ditra membrane underlayment.\nLay out tile pattern per client selection.\nInstall ceramic tile with proper thinset and spacers.\nGrout all joints with specified color.\nSeal grout lines and install baseboards and transition strips.",
    "Natural Stone Tile": "Remove existing flooring and prep subfloor \u2014 level and reinforce if needed for weight.\nInstall cement board underlayment rated for natural stone.\nDry-lay and plan pattern, accounting for natural color variation.\nInstall natural stone tile with white thinset to prevent discoloration.\nGrout with unsanded grout for polished stone or sanded for textured.\nSeal all stone surfaces with penetrating sealer \u2014 apply multiple coats.\nInstall baseboards and transition strips.",
    "Laminate": "Remove existing flooring and prep subfloor \u2014 level and clean.\nInstall foam underlayment with moisture barrier.\nInstall laminate flooring using click-lock system throughout specified areas.\nMaintain expansion gaps at all walls per manufacturer specs.\nInstall baseboards, shoe molding, and transition strips at all doorways.",
  },
  cabinets: {
    "Prefabricated Cabinets": "Verify kitchen layout dimensions match prefabricated cabinet order.\nInstall all base and upper cabinet boxes \u2014 level, shim, and secure to wall studs.\nInstall filler strips and end panels where cabinets meet walls.\nInstall all hardware \u2014 handles, pulls, knobs, and soft-close hinges.\nAdjust all doors and drawers for proper alignment and operation.",
    "Custom Cabinets": "Conduct on-site measurements and final field verification of all cabinet dimensions.\nCoordinate with cabinet maker on wood species, door style, finish, and hardware selections.\nReview and approve shop drawings before fabrication begins.\nInstall custom cabinet boxes \u2014 level, shim, and secure to wall studs and blocking.\nInstall all custom panels, moldings, and decorative elements.\nInstall all hardware per client selection \u2014 handles, pulls, knobs, specialty hinges.\nFine-tune all doors, drawers, and soft-close mechanisms for perfect alignment.\nTouch up any finish imperfections on site.",
    "Semi-Custom Cabinets": "Place order for semi-custom cabinets per approved kitchen layout \u2014 specify door style, finish, and modifications.\nInstall all base and upper cabinets \u2014 level, shim, and secure to wall studs.\nInstall fillers, end panels, and decorative moldings per design.\nInstall all hardware \u2014 handles, pulls, knobs, and hinges per client selection.\nAdjust all doors and drawers for proper alignment.",
    "Stock Cabinets": "Source and order stock cabinets per kitchen layout dimensions \u2014 confirm availability and sizes.\nInstall base and upper cabinets \u2014 level, shim, and secure to wall studs.\nInstall filler strips where standard sizes don\u2019t perfectly fit.\nInstall all hardware \u2014 handles, pulls, and hinges.\nAdjust doors and drawers for proper alignment and operation.",
    "Reface Existing Cabinets": "Inspect existing cabinet boxes for structural integrity \u2014 repair or reinforce as needed.\nRemove all existing doors, drawer fronts, and hardware.\nClean, sand, and prep all cabinet box surfaces.\nApply new veneer or laminate to all visible cabinet box surfaces \u2014 sides, face frames, and exposed ends.\nInstall new doors and drawer fronts per client selection \u2014 style and material.\nInstall new hardware \u2014 handles, pulls, knobs, and hinges.\nInstall new soft-close hinges and drawer slides.\nAdjust all doors and drawers for proper alignment.\nInstall new moldings and trim if specified.",
    "Paint Existing Cabinets": "Remove all cabinet doors, drawer fronts, and hardware \u2014 label each piece for reinstallation.\nClean all surfaces with TSP or degreaser to remove oils and residue.\nSand all surfaces with 150-grit for proper adhesion.\nFill any dents, scratches, or imperfections with wood filler \u2014 sand smooth.\nApply 1 coat of bonding primer (shellac-based or adhesion primer).\nApply 2\u20133 coats of cabinet-grade paint or lacquer \u2014 sand lightly between coats with 220-grit.\nReinstall all doors and drawer fronts with new or existing hardware.\nInstall new soft-close hinges if specified.\nAdjust all doors and drawers for proper alignment.",
  },
  countertops: {
    "Prefabricated Quartz": "Verify cabinet layout and dimensions for prefabricated quartz slab sizes.\nSelect prefab quartz slab from supplier \u2014 color and edge profile per client selection.\nInstall prefabricated quartz countertops \u2014 apply adhesive and secure to cabinet base.\nJoin sections with color-matched seam adhesive where needed.\nCut sink and cooktop openings on site if not pre-cut.\nCaulk all wall-to-countertop joints with color-matched silicone.\nClean and polish all surfaces.",
    "Quartz": "Template countertops after cabinets are installed and level \u2014 digital or physical template.\nFabricate custom quartz countertops from client-selected slab with specified edge profile.\nPolish edges and cutouts at fabrication shop.\nInstall countertops with proper support, shims, and adhesion.\nJoin sections with color-matched seam adhesive \u2014 minimize visible seams.\nCut and finish sink cutout and cooktop cutout if applicable.\nInstall backsplash return or waterfall edge if specified.\nCaulk all perimeter joints with silicone.",
    "Granite": "Template countertops after cabinets are installed \u2014 digital laser template preferred.\nAccompany client to slab yard for granite slab selection \u2014 review veining and color variation.\nFabricate countertops with specified edge profile \u2014 polish and seal edges.\nInstall granite countertops with proper support and adhesion.\nJoin sections with color-matched epoxy \u2014 minimize and align seams with natural veining.\nCut and finish sink and cooktop cutouts.\nSeal entire granite surface with penetrating stone sealer.\nCaulk all joints with color-matched silicone.",
    "Marble": "Template countertops after cabinets are installed.\nAccompany client to slab yard for marble selection \u2014 discuss veining direction and bookmatching.\nFabricate countertops with specified edge profile \u2014 hone or polish per client preference.\nInstall marble countertops with proper support and white adhesive (to prevent discoloration).\nJoin sections with color-matched epoxy \u2014 align veining across seams.\nCut and finish sink cutout.\nSeal with premium penetrating stone sealer \u2014 multiple coats recommended.\nNote: Marble is porous and requires regular resealing and careful maintenance.",
    "Butcher Block": "Select butcher block material \u2014 species, thickness, and grain pattern per client selection (maple, walnut, white oak).\nMeasure and cut butcher block to fit countertop layout \u2014 account for sink cutout.\nSand all surfaces smooth through progressive grits to 220.\nApply food-safe finish \u2014 mineral oil, tung oil, or hard wax oil per client preference.\nInstall butcher block on cabinet base with proper fasteners \u2014 allow for wood movement.\nApply silicone at sink cutout and wall joints.\nApply final coat of finish and buff.\nNote: Butcher block requires regular oiling and maintenance by homeowner.",
    "Laminate": "Verify cabinet layout dimensions for laminate countertop sizing.\nOrder laminate countertops in client-selected color and edge profile \u2014 standard or custom.\nInstall laminate countertops on cabinet base \u2014 secure with screws and adhesive.\nJoin sections with draw bolts and color-matched seam fill.\nCut sink and cooktop openings on site.\nInstall backsplash strip if included.\nCaulk all wall-to-countertop joints.",
    "Concrete": "Build custom forms on top of installed cabinets or on separate casting table.\nMix and pour concrete countertop with reinforcement (fiber mesh or rebar).\nEmbed sink molds and create cutouts during pour.\nAllow proper cure time per manufacturer specs.\nRemove forms and grind/polish surface to specified finish.\nFill any pinholes or voids with slurry.\nApply penetrating concrete sealer \u2014 multiple coats for stain resistance.\nInstall and level on cabinets if cast off-site.\nCaulk all perimeter joints.",
  },
  specialty_paint: {
    "Standard Interior Paint (Default)": "Prep all surfaces including patching holes, cracks, and imperfections with spackle or joint compound.\nSand all patched areas smooth and clean dust.\nCaulk all gaps at trim, baseboards and window/door casings.\nApply 1 coat of premium primer to all new and repaired surfaces.\nApply 2 coats of premium interior paint \u2014 brand and sheen per client selection.\nCut in all edges, corners, and trim lines by hand.\nRoll walls and ceilings with proper technique for even coverage.\nPaint all new trim, doors, and casings to match color scheme.\nProtect all flooring, fixtures, and finished surfaces during painting.\nPerform final touch-ups after all trades are complete.",
    "Limewash": "Prep all surfaces \u2014 walls must be smooth, clean, and free of loose paint or debris.\nApply base coat of compatible primer (mineral-based or limewash-specific).\nMix limewash to desired consistency and color \u2014 test on sample area for client approval.\nApply limewash using cross-hatch brush technique in thin, overlapping coats.\nAllow each coat to dry completely before applying next (2\u20134 coats typical).\nWork in manageable sections to maintain wet edge and avoid lap marks.\nVariation in tone and texture is characteristic of limewash \u2014 discuss expectations with client.\nSeal with breathable topcoat if specified for high-traffic areas.\nProtect all adjacent surfaces during application.",
    "Venetian Plaster": "Prep all surfaces \u2014 must be perfectly smooth (Level 5 drywall recommended).\nApply bonding primer compatible with plaster system.\nApply first coat of Venetian plaster with stainless steel trowel \u2014 thin, even coverage.\nAllow to dry and lightly sand any high spots.\nApply second coat at opposing angles to first \u2014 build depth and texture.\nAllow to dry and apply third coat if needed for desired depth and sheen.\nBurnish final coat with clean trowel using firm pressure to create characteristic high-gloss finish.\nSeal with wax or specialized plaster sealer for durability and stain resistance.\nNote: Venetian plaster is a specialized finish \u2014 labor intensive with longer timeline than standard paint.",
    "Roman Clay": "Prep all surfaces \u2014 walls must be smooth and primed with compatible primer.\nMix Roman clay to desired color \u2014 prepare test sample for client approval.\nApply first coat with flexible trowel in random, organic strokes \u2014 thin application.\nAllow to dry and sand lightly if needed.\nApply second coat using varied trowel angles to create dimensional texture.\nWork in small sections to maintain wet edge.\nBurnish or leave textured per client preference for desired look.\nSeal with wax or clear topcoat for moisture resistance.\nClean up all edges and transitions to adjacent surfaces.",
    "Microcement": "Prep all surfaces \u2014 must be structurally sound and properly primed with microcement-compatible primer.\nApply fiberglass mesh embedding coat for crack prevention.\nApply first base coat of microcement with stainless steel trowel \u2014 even, thin layer.\nAllow to cure and sand smooth.\nApply second coat of microcement \u2014 build to desired thickness and texture.\nSand between coats for smooth finish.\nApply sealer coat \u2014 polyurethane or epoxy topcoat per manufacturer specs.\nApply final wax coat for sheen and protection.\nNote: Microcement can be applied to walls, floors, and countertops \u2014 discuss full scope with client.",
  },
  tub_shower: {
    "Walk-In Shower": "Frame shower walls, curb, and niche openings per approved plan.\nInstall shower drain \u2014 linear or center drain per design.\nBuild shower pan with proper slope to drain \u2014 mud bed or prefab pan.\nApply waterproofing membrane to all shower surfaces \u2014 walls, floor, curb, and niche (Kerdi, RedGard, or equivalent).\nPerform flood test for 24 hours to verify waterproofing.\nInstall cement board or tile backer on all remaining walls.\nBuild shower bench if specified \u2014 waterproof all surfaces.\nInstall wall tile floor to ceiling per design.\nInstall floor tile with non-slip surface and proper slope.\nTile shower curb, niche, and bench surfaces.\nGrout, seal, and caulk all tile joints and transitions.",
    "Tub/Shower Combo": "Frame tub alcove to proper dimensions per tub specifications.\nSet and level tub \u2014 secure to wall studs with flange or clips.\nConnect tub drain and overflow.\nInstall cement board or tile backer on all walls above tub.\nApply waterproofing membrane to all wet areas.\nInstall wall tile from tub lip to ceiling or specified height.\nInstall tile accent band or niche if specified.\nGrout, seal, and caulk all joints \u2014 apply silicone at tub-to-tile transition.\nInstall shower valve trim, shower head, and tub spout.\nInstall shower curtain rod or glass enclosure if specified.",
    "Freestanding Tub": "Verify floor structure can support freestanding tub weight (filled with water).\nReinforce subfloor if needed per structural requirements.\nRough-in drain and supply lines at freestanding tub location \u2014 floor-mounted or wall-mounted per tub specs.\nSet tub in position \u2014 level and secure per manufacturer instructions.\nConnect drain, overflow, and supply lines.\nInstall freestanding tub filler \u2014 floor-mounted, wall-mounted, or deck-mounted per selection.\nTest all connections for leaks.\nCaulk base of tub to floor if specified.\nInstall any adjacent tile or finish work around tub area.",
    "Alcove Tub": "Frame tub alcove to proper dimensions \u2014 verify level and square.\nSet alcove tub in position \u2014 level from front to back and side to side.\nSecure tub flange to wall studs with roofing nails or screws.\nConnect drain and overflow assembly.\nInstall cement board or waterproof backer on walls above tub.\nApply waterproofing to all wet areas.\nInstall wall tile or surround panels per client selection.\nGrout, seal, and caulk all joints.\nInstall shower valve trim, shower head, and tub spout.\nApply silicone at all tub-to-wall transitions.",
    "Walk-In Tub": "Verify doorway access for walk-in tub delivery \u2014 may require door removal.\nReinforce subfloor to support filled tub weight.\nRemove existing tub and prep alcove or space for walk-in tub dimensions.\nSet walk-in tub in position \u2014 level and secure.\nConnect drain, overflow, supply lines, and electrical for jets/heater if applicable.\nInstall cement board and waterproof all surrounding walls.\nInstall wall tile or surround per client selection.\nTest door seal, drain, and all jet functions.\nInstall grab bars and safety features per manufacturer specs.",
    "Shower Pan (Tile-Ready)": "Set tile-ready shower pan on prepared subfloor \u2014 verify level and slope to drain.\nSecure pan per manufacturer instructions.\nConnect drain assembly and test for proper flow.\nApply waterproofing at all pan-to-wall transitions.\nInstall cement board on all shower walls.\nApply waterproofing membrane to walls and transitions.\nFlood test for 24 hours.\nInstall wall and floor tile per design.\nGrout, seal, and caulk all joints.",
  },
  siding: {
    "Stucco": "Install building paper or weather-resistant barrier (WRB) over sheathing.\nInstall metal lath (self-furred) with proper overlap and fastening.\nApply scratch coat of stucco \u2014 score surface for bonding.\nAllow scratch coat to cure per manufacturer specs.\nApply brown coat \u2014 level and plumb to specified thickness.\nAllow brown coat to cure per manufacturer specs.\nApply finish coat with specified texture \u2014 dash, skip trowel, sand, or lace.\nSeal all penetrations, joints, and transitions with backer rod and sealant.",
    "Smooth Stucco": "Install building paper or weather-resistant barrier over sheathing.\nInstall metal lath with proper overlap and fastening.\nApply scratch coat \u2014 score for bonding.\nAllow to cure per manufacturer specs.\nApply brown coat \u2014 float smooth and level.\nAllow brown coat to cure per manufacturer specs.\nApply finish coat using steel trowel for smooth finish \u2014 multiple passes to achieve glass-smooth surface.\nFill any pinholes or imperfections and re-trowel.\nNote: Smooth stucco requires highly skilled application and may show imperfections more readily than textured finishes.",
    "Hardie Board (Fiber Cement)": "Install weather-resistant barrier (WRB) over wall sheathing per manufacturer specs.\nInstall starter strip at base of wall.\nMeasure, cut, and install Hardie board siding \u2014 lap, panel, or board & batten style per design.\nMaintain proper overlap and spacing per manufacturer requirements.\nBlind-nail or face-nail per approved fastening schedule.\nFlash all windows, doors, and penetrations per manufacturer details.\nInstall corner boards, trim, and transition pieces.\nCaulk all butt joints and trim connections with paintable sealant.\nPrime all cut edges to maintain warranty.\nApply 2 coats of premium exterior paint per client color selection.",
    "Wood Siding": "Install weather-resistant barrier over sheathing.\nInstall furring strips for rainscreen gap if specified.\nMeasure, cut, and install wood siding \u2014 species per client selection (cedar, redwood, pine).\nInstall using stainless steel or hot-dipped galvanized fasteners to prevent staining.\nMaintain proper overlap, spacing, and ventilation per species requirements.\nFlash all openings and transitions.\nInstall corner boards and trim pieces.\nSand any rough spots and fill nail holes.\nApply stain, paint, or clear sealer per client preference \u2014 2 coats minimum.",
    "Vinyl Siding": "Install weather-resistant barrier over sheathing.\nInstall starter strip at base, level and plumb.\nInstall vinyl siding panels from bottom up \u2014 lock each course into previous.\nLeave proper expansion gaps at all termination points (1/4 inch typical).\nDo not over-nail \u2014 allow panels to move for thermal expansion.\nInstall J-channel around all windows, doors, and penetrations.\nInstall corner posts, soffit, and fascia trim.\nCut and fit around all utilities and fixtures.\nClean all installed surfaces.",
    "Board & Batten": "Install weather-resistant barrier over sheathing.\nInstall wide boards (8\u201312 inch) vertically \u2014 secure to studs or blocking.\nInstall narrow battens (2\u20133 inch) over board seams \u2014 secure through boards to framing.\nMaintain consistent spacing and plumb throughout.\nFlash all window, door, and penetration openings.\nInstall trim at corners, top, and base.\nFill all nail holes and sand smooth.\nApply primer and 2 coats exterior paint or stain per client selection.",
    "Stone Veneer": "Install weather-resistant barrier and metal lath over sheathing.\nApply scratch coat of morite and allow to cure.\nLay out stone pattern on ground before installation \u2014 plan corners and around openings.\nApply mortar bed to wall and back-butter each stone.\nSet stones from bottom up with proper joint spacing.\nInstall corner pieces first, then fill field stones.\nGrout joints with mortar bag \u2014 tool joints to specified profile.\nClean all stone surfaces with appropriate cleaner \u2014 no acid on natural stone.\nSeal with breathable stone sealer if specified.",
    "Brick Veneer": "Install weather-resistant barrier over sheathing.\nInstall metal lath and scratch coat.\nInstall metal shelf angle at base to support brick weight.\nLay brick veneer from bottom up with proper mortar joints \u2014 running bond or specified pattern.\nMaintain consistent joint width (3/8 inch typical).\nInstall weep holes and flashing at base and above all openings.\nInstall brick ties to wall framing at required spacing.\nTool all mortar joints to specified profile.\nClean brick with appropriate solution after mortar has set.",
  },
  roofing: {
    "Asphalt Shingles": "Remove existing roofing material down to decking \u2014 inspect and replace damaged sheathing.\nInstall ice and water shield at critical areas per code.\nInstall synthetic underlayment across entire roof deck.\nInstall new drip edge at eaves and rakes.\nInstall asphalt shingles per manufacturer specs \u2014 starter strip, field shingles, ridge cap.\nInstall step and counter flashing at all wall-to-roof transitions.\nFlash all penetrations \u2014 vents, pipes, skylights \u2014 with proper boot or custom flashing.\nInstall ridge vent for continuous ventilation.\nClean up all debris and nails \u2014 run magnet over property.\nObtain final roof inspection.",
    "Concrete Tile": "Remove existing roofing \u2014 inspect and repair sheathing as needed.\nVerify roof structure can support concrete tile weight (9\u201312 lbs/sqft) \u2014 reinforce if needed.\nInstall ice and water shield at eaves, valleys, and penetrations.\nInstall underlayment (min. 2 layers hot-mopped or synthetic) per code.\nInstall battens/counter-battens for tile attachment.\nInstall field tiles from eave to ridge \u2014 maintain proper overlap and alignment.\nCut and fit tiles at hips, valleys, and penetrations.\nInstall hip and ridge tiles with mortar or dry-ridge system.\nFlash all penetrations and transitions.\nClean roof of all debris and mortar drips.",
    "Clay Tile": "Remove existing roofing \u2014 inspect and repair sheathing.\nInstall ice and water shield and underlayment per code.\nInstall battens for tile attachment \u2014 spacing per tile profile.\nInstall field clay tiles from eave to ridge \u2014 handle carefully to prevent breakage.\nCut tiles with wet saw at hips, valleys, and penetrations.\nInstall hip and ridge tiles with mortar or mechanical fastening.\nFlash all transitions with metal flashing.\nSeal and waterproof all penetrations.\nClean roof surfaces of mortar and debris.",
    "Standing Seam Metal": "Remove existing roofing \u2014 inspect and repair sheathing as needed.\nInstall ice and water shield at eaves, valleys, and penetrations.\nInstall high-temp synthetic underlayment across entire deck.\nInstall eave drip edge and rake trim.\nMeasure and order custom-length standing seam metal panels \u2014 color per client selection.\nInstall panel clips at proper spacing per engineering.\nSnap-lock or mechanically seam panels from eave to ridge.\nInstall valley, hip, and ridge flashings \u2014 custom fabricated to match.\nFlash all penetrations with custom-fabricated boots or flashings.\nInstall gutter apron and snow guards if specified.\nTouch up any scratches with manufacturer-supplied paint.",
    "Flat Roof (TPO/Modified Bitumen)": "Remove existing flat roof membrane \u2014 inspect and repair decking.\nInstall new rigid insulation (polyiso) to achieve required R-value per Title 24.\nInstall tapered insulation system for proper drainage slope (1/4 inch per foot minimum).\nInstall cover board over insulation.\nInstall TPO or modified bitumen membrane \u2014 mechanically fastened, adhered, or torch-applied.\nWeld all seams with hot-air welder (TPO) or torch (mod-bit).\nInstall membrane up all parapet walls and curbs \u2014 minimum 8 inches.\nInstall new metal edge/coping at all perimeter edges.\nFlash all penetrations, drains, and scuppers.\nPerform flood test to verify waterproofing.\nInstall walkway pads at equipment access routes.",
    "Synthetic Slate": "Remove existing roofing \u2014 inspect and repair sheathing.\nInstall ice and water shield at eaves, valleys, and all critical areas.\nInstall synthetic underlayment across entire roof deck.\nInstall drip edge and starter course.\nInstall synthetic slate tiles per manufacturer pattern \u2014 stagger courses for natural appearance.\nCut and fit at hips, valleys, and penetrations.\nInstall hip and ridge cap pieces.\nFlash all penetrations and wall transitions.\nInstall ridge ventilation system.\nClean roof and property of all debris.",
    "Wood Shake": "Remove existing roofing \u2014 inspect and repair sheathing.\nInstall spaced or solid sheathing per code requirements and manufacturer specs.\nInstall ice and water shield at eaves, valleys, and penetrations.\nInstall interlayment (felt paper) between each course of shakes.\nInstall cedar shakes from eave to ridge \u2014 maintain proper exposure and offset.\nInstall hip and ridge shakes with proper overlap.\nFlash all penetrations and wall transitions with step and counter flashing.\nInstall ridge ventilation.\nApply wood preservative or fire retardant treatment if required by code.\nNote: Some jurisdictions restrict wood shake installation \u2014 verify local fire codes.",
  },
  insulation_type: {
    "Batt (Fiberglass)": "Install fiberglass batt insulation in all wall cavities \u2014 friction fit between studs.\nEnsure full coverage with no gaps, compression, or voids.\nCut and fit around electrical boxes, plumbing, and obstructions.\nInstall in ceiling cavities and floor cavities per plan.\nPass all required insulation and energy inspections.",
    "Batt (Mineral Wool/Rockwool)": "Install mineral wool (Rockwool) batt insulation in all wall cavities.\nFriction fit between studs \u2014 mineral wool holds shape without stapling.\nEnsure full coverage around outlets, pipes, and obstructions.\nInstall in ceiling and floor cavities per plan.\nMineral wool provides superior fire resistance and sound attenuation.\nPass insulation and energy inspections.",
    "Spray Foam (Open Cell)": "Mask and protect all surfaces not receiving spray foam.\nApply open-cell spray foam insulation to all specified wall, ceiling, and floor cavities.\nFill cavities completely \u2014 foam expands to fill gaps and air seal simultaneously.\nAllow foam to cure and trim excess flush with stud faces.\nOpen cell provides R-3.7/inch and excellent air sealing.\nInstall vapor retarder paint or membrane over open-cell foam in climate zones requiring it.\nPass insulation and energy inspections.",
    "Spray Foam (Closed Cell)": "Mask and protect all surfaces not receiving spray foam.\nApply closed-cell spray foam to specified cavities \u2014 typically 2\u20133 inches per pass.\nClosed cell provides R-6.5/inch, air barrier, and vapor barrier in one application.\nAllow each pass to cure before applying additional thickness.\nTrim excess foam flush with stud faces.\nClosed cell adds structural rigidity to wall assembly.\nIdeal for crawl spaces, rim joists, and moisture-prone areas.\nPass insulation and energy inspections.",
    "Blown-In Cellulose": "Install netting or membrane over open wall cavities to contain cellulose.\nBlow cellulose insulation into wall cavities to specified density (3.5 lbs/cu ft for walls).\nEnsure complete fill with no settling gaps.\nBlow cellulose into attic or ceiling cavities to specified depth and R-value.\nCellulose provides excellent air sealing and sound attenuation.\nPass insulation and energy inspections.",
  },
  mini_split: {
    "Wall-Mounted Mini Split": "Install outdoor condenser unit on concrete pad or wall bracket \u2014 per manufacturer specs.\nRun refrigerant line set, condensate drain, and electrical from outdoor unit to each indoor head.\nMount wall-mounted indoor unit(s) at specified location.\nConnect refrigerant lines, electrical, and condensate drain to each head.\nVacuum and charge refrigerant system.\nInstall line set cover on exterior for clean appearance.\nPass all required HVAC inspections.",
    "Ceiling Cassette": "Install outdoor condenser unit on concrete pad or wall bracket.\nFrame and prep ceiling opening for cassette unit \u2014 typically 2x2 ft.\nRun refrigerant lines, condensate drain, and electrical through ceiling/attic space.\nInstall ceiling cassette flush with finished ceiling \u2014 4-way air distribution.\nConnect all refrigerant, drain, and electrical connections.\nVacuum and charge system.\nInstall decorative ceiling grille panel.\nProgram controls and test all modes.\nPass HVAC inspections.",
    "Ducted Mini Split": "Install outdoor condenser unit per manufacturer specs.\nInstall concealed indoor air handler in attic, closet, or soffit space.\nRun refrigerant lines, condensate drain, and electrical from condenser to air handler.\nInstall insulated flex duct from air handler to supply registers in each room.\nInstall return air duct and grille.\nConnect all refrigerant, drain, and electrical.\nVacuum and charge system.\nInstall supply registers and return grilles \u2014 flush with ceiling or wall.\nPass HVAC inspections.",
    "Multi-Zone System": "Install outdoor multi-zone condenser unit \u2014 sized for total BTU load of all zones.\nRun individual refrigerant line sets from condenser to each indoor unit.\nInstall indoor units per zone \u2014 wall-mount, ceiling cassette, or ducted per room.\nRun condensate drains from each indoor unit to exterior or drain.\nRun electrical to condenser and each indoor unit.\nConnect all refrigerant lines, drain, and electrical at each unit.\nVacuum entire system and charge with proper refrigerant amount.\nProgram individual zone controls and master controller.\nTest each zone independently and in combination.\nPass all required HVAC inspections.",
    "Central HVAC": "Install or replace central air handler and condensing unit \u2014 sized per Manual J load calculation.\nInstall or extend ductwork throughout \u2014 supply runs, return air, and registers per mechanical plan.\nInstall plenum, trunk lines, and insulated flex duct to all rooms.\nInstall supply registers and return grilles flush with ceiling or wall.\nInstall programmable or smart thermostat.\nConnect all refrigerant lines, condensate drain, and electrical.\nVacuum and charge system.\nBalance airflow to all zones.\nPass all required HVAC inspections.",
  },
} as const;
