// ============================================================
// PROJECT SCOPES — Complete scope items per project type
// Extracted from intake.jsx lines 407-982
// ============================================================

export interface ScopeItemDef {
  id: string;
  label: string;
  desc: string;
  std?: boolean;
  opt?: boolean;
  finishKey?: string;
  finishKey2?: string;
}

export const PROJECT_SCOPES: Record<string, ScopeItemDef[]> = {
  // ── INTERIOR REMODEL ──
  interior_remodel: [
    { id: "i1", label: "Design, Architectural & Engineering Plans", std: true, desc: "Conduct multiple in-depth meetings with the client to fully understand their design preferences, lifestyle needs, and aesthetic goals.\nDiscuss design styles and explore functional priorities.\nAllow time for multiple rounds of feedback, revisions, and updates.\nDevelop detailed architectural plans including floor plans, elevations, sections, and construction documents.\nAssist in the permit acquisition process through the local building department.\nWork with a structural engineer to ensure design feasibility and structural integrity." },
    { id: "i2", label: "Demolition & Haul Away", desc: "Protect all surfaces, fixtures, and finishes outside the work area with coverings and dust barriers.\nDemo according to approved demolition plan.\nHaul and dump all debris and trash throughout the duration of the project.\nMaintain a clean and safe work environment at all times." },
    { id: "i3", label: "Bearing Wall Removal & Layout Change", desc: "Install temporary support walls to ensure structural stability before demolition.\nDemo existing walls per engineering and architectural plans.\nFrame and install support beams, headers, and posts per structural engineer\u2019s specifications.\nInstall bearing pads and posts per engineering plan.\nDrywall, tape, mud, texture, and paint all exposed areas to match existing wall finishes." },
    { id: "i4", label: "Framing & Structural", desc: "Frame new walls, hallways, and door openings per approved architectural plans.\nFrame new closets, niches, and built-in areas as specified.\nInstall blocking for cabinets, handrails, TV mounts, and other wall-mounted fixtures.\nPass all required framing inspections to ensure compliance with building codes." },
    { id: "i5", label: "Electrical \u2014 Rough", desc: "Run all new electrical circuits, outlets, and switch locations per approved plans.\nInstall dedicated circuits for appliances, HVAC, and other high-draw equipment.\nInstall all junction boxes, conduit, and wiring.\nPass rough electrical inspection." },
    { id: "i5b", label: "Electrical \u2014 Finish", desc: "Install recessed lighting, pendant fixtures, under-cabinet lighting, and decorative fixtures.\nInstall all switches, dimmers, outlets, and cover plates.\nInstall smoke detectors and CO detectors per code.\nTest all circuits and verify operation.\nPass final electrical inspection." },
    { id: "i6", label: "Plumbing \u2014 Rough", desc: "Rough-in all new plumbing supply and drain lines per approved plans.\nRelocate or add plumbing fixtures as required by the new layout.\nInstall shut-off valves at all new fixture locations.\nPass rough plumbing inspection." },
    { id: "i6b", label: "Plumbing \u2014 Finish", desc: "Connect and test all fixtures including sinks, faucets, and supply lines.\nInstall garbage disposal and appliance hookups.\nInstall all plumbing trim and accessories.\nTest for leaks and verify operation.\nPass final plumbing inspection." },
    { id: "i7", label: "HVAC / Mini Split", desc: "Extend or modify existing HVAC ductwork to serve new or reconfigured spaces.\nInstall new supply and return vents per approved mechanical plan.\nInstall mini split system(s) for supplemental or primary heating/cooling if specified.\nEnsure proper airflow and climate control throughout the remodeled areas.\nPass all required HVAC inspections.", finishKey: "mini_split" },
    { id: "i8", label: "Insulation", desc: "Install insulation in all new and opened per Title 24 energy requirements.\nInsulate ceiling cavities and any exposed floor areas per code.\nPass all required insulation and energy inspections.", finishKey: "insulation_type" },
    { id: "i9", label: "Drywall, Tape, Mud & Texture", desc: "Hang drywall on all new and opened framed walls and ceilings.\nTape, mud, and sand all joints and seams to specified finish level.\nApply texture to match existing or per client selection.\nPrepare all surfaces for primer and paint.", finishKey: "drywall_level", finishKey2: "drywall_texture" },
    { id: "i10", label: "Interior Doors & Hardware", desc: "Install new interior doors per plan \u2014 style and material selected by client.\nInstall all door hardware including handles, hinges, and stops.\nApply trim and casing around all new door openings to match existing or new trim profile.\nAdjust and align all doors for proper fit and operation.", finishKey: "doors" },
    { id: "i11", label: "Flooring Installation", desc: "Remove existing flooring as needed and prep subfloor for new material.\nInstall new flooring throughout specified areas.\nInstall baseboards, shoe molding, and transition strips at all thresholds and material changes.\nEnsure all seams, edges, and transitions are clean and properly finished.", finishKey: "flooring" },
    { id: "i12", label: "Interior Paint", desc: "Prep all surfaces including patching, sanding, caulking, and priming as needed.\nApply two coats of premium interior paint to all new and existing walls within the scope.\nPaint all new trim, doors, and casings to match client\u2019s selected color scheme.\nProtect all flooring, fixtures, and finished surfaces during painting.", finishKey: "specialty_paint" },
    { id: "i13", label: "Trim, Baseboards & Millwork", desc: "Install new baseboards and window/door casings per design plan.\nInstall wainscoting, chair rail, or accent molding where specified.\nFill all nail holes, caulk joints, and sand smooth before paint." },
    { id: "i14", label: "Bedroom Reconfiguration", desc: "Create new room layout per approved architectural plan.\nFrame new walls, closets, and door openings.\nSplit or reconfigure rooms including framing, blocking, and headers.\nReroute electrical circuits, switches, and outlets per new layout.\nInstall drywall, tape, mud, texture, and paint to match.\nInstall new doors, hardware, and trim." },
    { id: "i15", label: "Window Replacement", desc: "Remove existing windows and prepare openings for new units.\nInstall new energy-efficient windows \u2014 style and material selected by client.\nFlash, seal, and weatherproof all window openings per manufacturer specs.\nInstall interior and exterior trim and casing.\nPass all required inspections.", finishKey: "windows" },
    { id: "i16", label: "Closet Build-Out", desc: "Frame new closet spaces per approved plans.\nInstall closet shelving systems, rods, and organizer components.\nInstall closet doors \u2014 sliding, bifold, or hinged per client selection.\nDrywall, paint, and trim interior of all new closet spaces." },
    { id: "i18", label: "Hardwood Floor Restoration", desc: "Inspect and assess condition of existing hardwood floors \u2014 identify damage, wear, stains, and gaps.\nSand all hardwood surfaces using progressive grits to remove old finish and level the surface.\nFill gaps, cracks, and nail holes with matching wood filler.\nRepair or replace damaged boards as needed.\nApply wood stain if specified by client.\nApply 3 coats of polyurethane finish (water-based or oil-based per client preference).\nLight sand between coats for proper adhesion.\nProtect finished floors during remaining construction phases.", finishKey: "flooring" },
    { opt: true, id: "i19", label: "Roof Tear-Off & Demo", desc: "Set up temporary weather protection before roof removal.\nRemove all existing roofing material down to the roof deck.\nInspect roof deck/sheathing for rot, damage, or deterioration.\nReplace any damaged plywood or OSB sheathing with new material.\nHaul and dump all old roofing materials.\nInstall protective tarps and barriers during tear-off." },
    { opt: true, id: "i20", label: "Roof Deck Inspection & Repair", desc: "Inspect entire roof deck for rot, soft spots, and structural damage.\nReplace any rotted or damaged plywood/OSB sheathing.\nRe-nail or re-secure any loose sheathing to rafters.\nInstall additional blocking or framing reinforcement where needed.\nEnsure entire roof deck is solid, level, and ready for new roofing." },
    { opt: true, id: "i21", label: "New Roof Installation", desc: "Install synthetic underlayment over entire roof deck.\nInstall ice & water shield at critical areas per code.\nInstall new roofing material per approved plan.\nInstall starter course, field material, and ridge cap.\nFlash all roof-to-wall transitions, valleys, and penetrations.\nInstall drip edge at all eaves and rakes.\nInstall ridge vent for proper attic ventilation.\nInstall gutters and downspouts per plan.\nPerform magnetic nail sweep and clean-up.", finishKey: "roofing" },
    { std: true, id: "int_ka1", label: "Kitchen \u2014 Cabinets", desc: "Install all base and upper cabinets per approved kitchen layout.\nLevel, shim, and secure to wall studs and blocking.\nInstall all hardware \u2014 handles, pulls, knobs, hinges.", finishKey: "cabinets" },
    { std: true, id: "int_ka2", label: "Kitchen \u2014 Countertops", desc: "Template countertops after cabinets are installed.\nFabricate with specified edge profile.\nInstall with proper support and seams.\nCut sink and cooktop cutouts.", finishKey: "countertops" },
    { std: true, id: "int_ka3", label: "Kitchen \u2014 Backsplash", desc: "Prep wall surfaces and install backsplash per design.\nGrout, seal, and clean all surfaces.\nInstall edge trim at all exposed edges.", finishKey: "backsplash" },
    { std: true, id: "int_ka4", label: "Kitchen \u2014 Flooring", desc: "Remove existing kitchen flooring and prep subfloor.\nInstall new kitchen flooring.\nInstall baseboards and transition strips.", finishKey: "flooring" },
    { std: true, id: "int_ka5", label: "Kitchen \u2014 Plumbing Fixtures", desc: "Install kitchen sink \u2014 undermount, farmhouse, or other per design.\nInstall faucet, sprayer, soap dispenser, and accessories.\nInstall and wire garbage disposal.\nConnect dishwasher drain and supply." },
    { std: true, id: "int_ka6", label: "Kitchen \u2014 Range Hood & Venting", desc: "Install range hood with ductwork vented to exterior.\nEnsure adequate supply and return air to kitchen." },
    { std: true, id: "int_ka7", label: "Kitchen \u2014 Appliance Installation", desc: "Receive and install all client-purchased appliances.\nEnsure proper electrical, gas, and plumbing connections.\nVerify all appliances are level, secured, and operational.\nNote: Company will not install high-end appliances \u2014 to be installed by distributor/manufacturer." },
    { std: true, id: "int_ka8", label: "Kitchen \u2014 Lighting", desc: "Install recessed lights, pendants, and under-cabinet LEDs.\nInstall all switches, dimmers, and smart controls." },
    { std: true, id: "int_ba1", label: "Bathroom \u2014 Tub/Shower", desc: "Install tub or shower base per design.\nWaterproof all wet areas with membrane system.\nInstall cement board or tile backer on all wet walls.\nBuild bench, curb, and niche per design.\nFlood test to verify waterproofing.", finishKey: "tub_shower" },
    { std: true, id: "int_ba2", label: "Bathroom \u2014 Tile Work", desc: "Install wall tile in shower/tub surround \u2014 floor to ceiling or per design.\nInstall floor tile with proper slope to drain.\nInstall accent tile and niche tile per design.\nGrout, seal, and clean all surfaces." },
    { std: true, id: "int_ba3", label: "Bathroom \u2014 Vanity & Countertop", desc: "Install vanity cabinet and countertop.\nInstall undermount or vessel sink per design.\nInstall faucet, drain assembly, and mirror.\nConnect plumbing supply and drain.", finishKey: "vanity" },
    { std: true, id: "int_ba4", label: "Bathroom \u2014 Shower Glass", desc: "Measure and order frameless or semi-frameless glass enclosure per design.\nInstall glass door and panels with proper hardware and seals.\nAlign, adjust, and silicone all glass components." },
    { std: true, id: "int_ba5", label: "Bathroom \u2014 Toilet & Fixtures", desc: "Install toilet with wax ring, bolts, and supply line.\nInstall all plumbing trim and escutcheons.\nInstall towel bars, TP holder, robe hooks, and all accessories." },
    { std: true, id: "int_ba6", label: "Bathroom \u2014 Lighting & Exhaust", desc: "Install vanity light fixture, recessed lights, and accent lighting.\nInstall exhaust fan \u2014 standard or combination fan/light/heater unit.\nInstall all switches, dimmers, and cover plates." },
    { id: "i17", label: "Final Clean & Punch List", desc: "Perform thorough final cleaning of all work areas including dusting, vacuuming, and wiping all surfaces.\nConduct detailed walk-through with client to identify any remaining punch list items.\nComplete all punch list items.\nRemove all construction materials, tools, and debris from the property." },
  ],

  // ── KITCHEN REMODEL ──
  kitchen_remodel: [
    { id: "k1", label: "Design, Architectural & Engineering Plans", std: true, desc: "Conduct initial consultation and follow-up meetings to understand client\u2019s kitchen workflow, storage needs, and design preferences.\nDevelop detailed kitchen layout including cabinet placement, appliance locations, island configuration, and lighting plan.\nPrepare architectural drawings and construction documents for permit submission.\nCoordinate with structural engineer if bearing walls are being modified.\nAssist in permit acquisition through local building department." },
    { id: "k0a", label: "Layout Change / Plumbing Reroute", desc: "Determine if the kitchen layout is changing and whether plumbing fixtures need to be rerouted.\nIdentify sink, dishwasher, and island plumbing relocation requirements.\nAssess impact on existing drain lines, venting, and supply routing.\nCoordinate with structural engineer if slab work or foundation penetrations are needed.", finishKey: "layout_change" },
    { id: "k2", label: "Demolition & Haul Away", desc: "Remove all existing cabinets, countertops, backsplash, flooring, and fixtures within the kitchen scope.\nCap and protect all plumbing and electrical during demolition.\nSet up dust barriers and floor protection to contain debris.\nHaul and dump all demolition materials throughout the project." },
    { id: "k3", label: "Bearing Wall Removal / Layout Change", desc: "Install temporary shoring and support before any structural demolition.\nRemove bearing walls or partial walls per structural engineer\u2019s plan.\nInstall engineered beams, headers, posts, and connection hardware per approved plans.\nFrame new wall locations, pass-throughs, or openings per architectural plan.\nPatch and finish all affected ceiling and wall surfaces." },
    { id: "k4", label: "Framing & Structural", desc: "Frame new walls, soffits, and openings per approved kitchen layout.\nInstall blocking for upper cabinets, range hood, TV mount, and shelving.\nFrame island base and any peninsula or bar areas.\nEnsure all framing meets code and passes required inspections." },
    { id: "k5", label: "Electrical", desc: "Install dedicated 20-amp circuits for countertop receptacles per code (GFCI protected).\nInstall dedicated circuits for range/oven, dishwasher, disposal, microwave, and refrigerator.\nRough-in wiring for recessed lighting, pendant lights.\nInstall all switches, dimmers, outlets, and cover plates.\nPass all required electrical inspections." },
    { id: "k6", label: "Plumbing", desc: "Rough-in supply and drain lines for kitchen sink in new or relocated position.\nInstall dedicated supply lines for dishwasher, refrigerator water line, and pot filler if specified.\nInstall new shut-off valves at all fixture locations.\nConnect and test all plumbing fixtures, garbage disposal, and appliance hookups.\nPass all required plumbing inspections." },
    { id: "k7", label: "HVAC / Range Hood Venting", finishKey: "mini_split", desc: "Install range hood ductwork and vent to exterior per manufacturer specifications.\nModify existing HVAC ductwork if kitchen layout has changed.\nEnsure adequate supply and return air to the kitchen area.\nPass all required mechanical inspections." },
    { id: "k8", label: "Insulation & Drywall", desc: "Insulate any new or opened per Title 24 energy code.\nHang, tape, mud, and sand all joints to specified finish level.\nApply texture to match existing or per client selection.\nPrepare all surfaces for primer and paint.", finishKey: "drywall_level", finishKey2: "drywall_texture" },
    { id: "k9", label: "Cabinet Installation", desc: "Install all base and upper cabinets per approved kitchen layout.\nLevel, shim, and secure all cabinets to wall studs and blocking.\nInstall all cabinet hardware \u2014 handles, pulls, knobs, and hinges per client selection.\nAdjust all doors and drawers for proper alignment and operation.", finishKey: "cabinets" },
    { id: "k10", label: "Countertop Fabrication & Installation", desc: "Template countertops after cabinets are installed and level.\nFabricate countertops from client-selected material with specified edge profile.\nInstall countertops with proper support, seams, and adhesion.\nCut and finish sink cutout and cooktop cutout if applicable.\nInstall backsplash return or waterfall edge if specified.", finishKey: "countertops" },
    { id: "k11", label: "Backsplash Installation", desc: "Prep wall surfaces behind countertop for backsplash installation.\nInstall backsplash per design layout \u2014 material and pattern selected by client.\nGrout, seal, and clean all tile/slab surfaces.\nInstall edge trim or finishing pieces at all exposed edges.", finishKey: "backsplash" },
    { id: "k12", label: "Flooring Installation", desc: "Remove existing kitchen flooring and prep subfloor for new material.\nInstall new flooring throughout kitchen.\nInstall baseboards, shoe molding, and transition strips at all doorways and material changes.\nEnsure proper expansion gaps and moisture barriers where required.", finishKey: "flooring" },
    { id: "k13", label: "Plumbing Fixtures & Connections", desc: "Install kitchen sink \u2014 style and material per client selection (undermount, farmhouse, etc.).\nInstall faucet, sprayer, soap dispenser, and accessories.\nInstall and wire garbage disposal unit.\nConnect dishwasher drain, supply, and electrical.\nTest all connections for leaks and proper operation." },
    { id: "k14", label: "Appliance Installation", desc: "Receive and install all client-purchased appliances.\nEnsure proper electrical, gas, and plumbing connections.\nVerify all appliances are level, secured, and operational.\nNote: Appliances are owner-supplied unless otherwise agreed. Company will not install high-end appliances \u2014 to be installed by distributor/manufacturer." },
    { id: "k15", label: "Interior Paint", desc: "Prep and prime all new drywall surfaces, patched areas, and trim.\nApply two coats of premium paint (limewash, Venetian plaster, Roman clay, etc.) to kitchen walls and ceiling.\nPaint all trim, casings, and door frames to match client\u2019s color scheme.\nPerform final touch-ups after all trades are complete.", finishKey: "specialty_paint" },
    { id: "k16", label: "Lighting & Fixtures", desc: "Install all recessed lights, pendant fixtures, and chandeliers per lighting plan.\nInstall under-cabinet LED lighting with switch or dimmer control.\nInstall all decorative fixtures, sconces, and accent lighting.\nProgram and test all dimmers and smart switches if applicable." },
    { id: "k17", label: "Final Clean & Punch List", desc: "Perform detailed final clean of all kitchen surfaces, cabinets, appliances, and fixtures.\nConduct walk-through with client to review all completed work.\nAddress and complete all punch list items.\nRemove all construction materials and debris from the property." },
  ],

  // ── BATHROOM REMODEL ──
  bathroom_remodel: [
    { id: "b1", label: "Design & Plans", std: true, desc: "Consult with client on bathroom layout, fixture placement, tile design, and storage needs.\nPrepare detailed bathroom floor plan and elevation drawings.\nSelect and specify all fixtures, finishes, and materials with client.\nSubmit for permits if required by scope of work." },
    { id: "b0a", label: "Layout Change / Fixture Reroute", desc: "Determine if the bathroom layout is changing and whether fixtures need to be rerouted.\nIdentify toilet, vanity, tub/shower relocation requirements.\nAssess impact on existing drain lines, venting, and supply routing.\nCoordinate with structural engineer if slab work is needed for drain relocation.", finishKey: "layout_change" },
    { id: "b2", label: "Demolition & Haul Away", desc: "Remove all existing fixtures including vanity, toilet, tub/shower, mirrors, and accessories.\nDemo existing tile, flooring, and wall surfaces within scope.\nCap all plumbing and protect electrical during demo.\nSet up dust barriers and haul all debris throughout the project." },
    { id: "b3", label: "Framing & Layout Changes", desc: "Frame new walls, niches, or half-walls per approved bathroom layout.\nFrame shower bench, curb, and niche openings.\nInstall blocking for grab bars, shower glass, vanity mirror, and accessories.\nRelocate door opening if specified in the plan." },
    { id: "b4", label: "Plumbing Rough-In", desc: "Relocate or install new supply and drain lines for tub/shower, vanity, and toilet.\nInstall new shut-off valves at all fixture locations.\nInstall shower valve and diverter per client\u2019s fixture selection.\nRough-in for body sprays, handheld shower, or rain head if specified.\nPass all required plumbing inspections." },
    { id: "b5", label: "Electrical", desc: "Install GFCI-protected outlets per code \u2014 vanity area and general use.\nRun circuits for exhaust fan, towel warmer, and lighting.\nRough-in wiring for vanity lights, recessed lights, and any accent lighting.\nInstall exhaust fan rated for bathroom size and duct to exterior.\nPass all required electrical inspections." },
    { id: "b6", label: "Tub / Shower Installation", desc: "Install new tub or shower base/pan \u2014 type selected by client.\nWaterproof all shower walls and floor using membrane system (Kerdi, RedGard, or equivalent).\nInstall cement board or tile backer on all wet-area walls.\nBuild shower bench, curb, and recessed niche per design.\nPerform flood test to verify waterproofing before tile.", finishKey: "tub_shower" },
    { id: "b7", label: "Tile Work", desc: "Install wall tile in shower/tub surround.\nInstall floor tile throughout bathroom with proper slope to drain.\nInstall accent tile, listello, or mosaic niche tile per design.\nGrout all tile joints with specified grout color.\nSeal all grout lines and natural stone surfaces.\nInstall tile edge trim at all exposed edges and transitions." },
    { id: "b8", label: "Vanity, Countertop & Mirror", finishKey2: "vanity", desc: "Install bathroom vanity \u2014 single or double per client selection.\nInstall countertop with sink cutout(s).\nSecure vanity to wall studs and level.\nInstall all vanity hardware, soft-close hinges, and drawer slides.\nConnect plumbing supply and drain.", finishKey: "countertops" },
    { id: "b9", label: "Plumbing Fixtures & Trim", desc: "Install faucet(s), drain assemblies, and pop-up stops at vanity.\nInstall shower valve trim, shower head, and hand-held sprayer.\nInstall toilet \u2014 style per client selection.\nConnect and test all fixtures for leaks and proper operation.\nInstall toilet accessories (seat, supply line, etc.)." },
    { id: "b10", label: "Shower Glass / Enclosure", desc: "Measure and order frameless or semi-frameless glass enclosure per design.\nInstall shower glass door and fixed panels with proper hardware.\nSeal all glass-to-tile connections with silicone.\nVerify smooth operation of door and hardware.\nNote: Lead time for custom glass is typically 2\u20134 weeks." },
    { id: "b11", label: "Drywall, Interior Paint", desc: "Hang, tape, mud, and texture all new and repaired drywall surfaces.\nUse moisture-resistant drywall (green board or purple board) in all wet areas.\nPrime and apply two coats of premium paint (limewash, Venetian plaster, Roman clay, etc.).\nPaint all trim, door, and casings to match.", finishKey: "specialty_paint" },
    { id: "b12", label: "Accessories & Final", desc: "Install mirrors, medicine cabinets, and vanity lighting.\nInstall towel bars, robe hooks, toilet paper holder, and shower accessories.\nInstall grab bars if specified (ADA or aging-in-place).\nCaulk all fixtures, trim, and transitions.\nPerform final walk-through and complete punch list items." },
    { id: "b13", label: "Flooring", desc: "Remove existing bathroom flooring and prep subfloor.\nInstall waterproof membrane under floor tile if applicable.\nInstall floor tile with proper slope and grout.\nInstall baseboards and transition strips.", finishKey: "flooring" },
  ],

  // ── NEW BATHROOM / POWDER ROOM ──
  new_bathroom: [
    { id: "nb0", label: "Layout & Plumbing Planning", std: true, desc: "Consult with client on bathroom location, size, layout, and intended use (full bath, 3/4 bath, half bath / powder room).\nDevelop architectural plans showing new bathroom layout with fixture placement, dimensions, and door swing.\nCoordinate with structural engineer if any load-bearing modifications are required.\nPrepare Title 24 energy calculations if applicable.\nSubmit for permit and manage plan check process.", finishKey: "layout_change" },
    { id: "nb1", label: "Demolition & Prep", desc: "Protect all existing surfaces and finishes outside the work area with coverings and dust barriers.\nRemove existing wall finishes, flooring, and ceiling in the area designated for the new bathroom.\nSaw-cut and remove slab or subfloor sections for new drain lines.\nCap and protect existing utilities during demolition.\nHaul and dump all debris throughout the project." },
    { id: "nb2", label: "Framing", desc: "Frame all new partition walls for the bathroom per approved plan.\nFrame door opening with proper header and cripple studs.\nInstall blocking in all walls for vanity, mirrors, grab bars, shower glass, towel bars, and accessories.\nFrame shower niche(s) and any built-in shelving per design.\nFrame for exhaust fan, lighting, and any ceiling details.\nPass all required framing inspections." },
    { id: "nb3", label: "Plumbing \u2014 Rough", desc: "Rough-in all new plumbing supply and drain lines per approved plans.\nInstall toilet flange, vanity supply/drain, and shower/tub supply and drain in proper locations.\nInstall shut-off valves at all fixture locations.\nInstall shower valve rough-in at proper height per plan.\nVent all fixtures per plumbing code.\nPass all required rough plumbing inspections." },
    { id: "nb4", label: "Plumbing \u2014 Finish", desc: "Install toilet and connect to flange with proper wax ring and bolts.\nInstall vanity faucet, drain assembly, and supply lines.\nInstall shower valve trim, diverter, shower head, and hand shower per client selection.\nInstall all plumbing trim, escutcheons, and accessories.\nTest all connections for leaks and verify proper drainage.\nPass all required final plumbing inspections." },
    { id: "nb5", label: "Electrical \u2014 Rough", desc: "Run all new electrical circuits per approved plans.\nInstall dedicated circuit for exhaust fan.\nInstall outlet, switch, and lighting boxes per plan.\nInstall GFCI protection for all bathroom outlets per code.\nPass rough electrical inspection." },
    { id: "nb6", label: "Electrical \u2014 Finish", desc: "Install all outlets, switches, dimmers, and cover plates.\nInstall vanity light fixture, recessed lights, and any decorative lighting.\nInstall exhaust fan \u2014 standard or combination fan/light/heater unit.\nTest all circuits and pass final electrical inspection." },
    { id: "nb7", label: "Insulation & Drywall", desc: "Install insulation in all new and exterior walls per Title 24.\nHang moisture-resistant drywall (green board or purple board) on all walls and ceiling.\nTape, mud, and sand all joints to specified finish level.\nApply texture per client selection.", finishKey: "insulation_type" },
    { id: "nb8", label: "Waterproofing & Tile", desc: "Apply waterproofing membrane to all shower walls, floor, curb, and niche(s) \u2014 Kerdi, RedGard, or equivalent.\nInstall shower pan with proper slope to drain \u2014 prefab base or custom mud bed.\nInstall wall tile in shower area \u2014 floor to ceiling or per design.\nInstall floor tile throughout bathroom with proper slope and non-slip surface.\nInstall tile on shower curb, niche, and any accent areas.\nGrout, seal, and caulk all tile joints and transitions.", finishKey: "tub_shower" },
    { id: "nb9", label: "Vanity, Countertop & Mirror", finishKey2: "vanity", desc: "Install vanity cabinet \u2014 single or double per plan and client selection.\nInstall countertop \u2014 prefab quartz, marble, or other per client selection.\nInstall undermount or vessel sink per design.\nInstall mirror \u2014 framed or frameless per client selection.\nSecure all components to wall with proper blocking and hardware.", finishKey: "countertops" },
    { id: "nb10", label: "Shower Glass", desc: "Measure and order shower glass enclosure per design \u2014 frameless, semi-frameless, or framed.\nInstall glass door and panels with proper hardware and seals.\nAlign, adjust, and silicone all glass components." },
    { id: "nb11", label: "Interior Paint", desc: "Prep all surfaces including patching, sanding, caulking, and priming.\nApply two coats of premium moisture-resistant paint to all walls and ceiling.\nPaint door, trim, and casings to match client selection.", finishKey: "specialty_paint" },
    { id: "nb12", label: "Door, Trim & Accessories", desc: "Install bathroom door with hardware \u2014 privacy lock set per client selection.\nInstall baseboards, door casing, and any crown molding.\nInstall towel bars, toilet paper holder, robe hooks, and all accessories.\nInstall shower shelf, corner caddy, or other storage accessories.", finishKey: "doors" },
    { id: "nb13", label: "Final Clean & Punch List", desc: "Perform thorough final cleaning of the new bathroom.\nConduct detailed walk-through with client to identify punch list items.\nComplete all punch list items." },
  ],

  // ── 1ST STORY ADDITION ──
  addition_1st: [
    { id: "a1_1", label: "Design, Architectural & Engineering Plans", std: true, desc: "Meet with client to define the addition scope, room types, and design goals.\nDevelop architectural plans including floor plans, elevations, sections, roof plan, and construction details.\nCoordinate structural engineering for foundation, framing, and connection to existing structure.\nPrepare Title 24 energy calculations and any required soils/geotechnical reports.\nSubmit plans for permit and assist through plan check revisions." },
    { id: "a1_2", label: "Site Prep & Excavation", desc: "Survey and stake addition footprint per approved site plan.\nExcavate for foundation per geotechnical and structural engineer\u2019s specifications.\nGrade and compact soil to proper bearing capacity.\nInstall temporary shoring if required to protect existing structure.\nManage soil export and debris removal." },
    { id: "a1_3", label: "Foundation", desc: "Form and pour continuous or spread footings per structural plan.\nInstall anchor bolts, hold-downs, and connection hardware per engineering.\nPour stem walls and/or slab on grade per approved foundation plan.\nInstall moisture barrier and underslab insulation per code.\nPass all required foundation inspections before backfill.", finishKey: "foundation" },
    { id: "a1_4", label: "Framing", desc: "Frame all exterior and interior walls per approved architectural plans.\nInstall floor framing, joists, and subfloor \nFrame roof structure including rafters, ridge beam, and ceiling joists per structural plan.\nInstall engineered beams, headers, and posts per structural engineer\u2019s specifications.\nInstall shear wall, hold-down, and tie-down hardware per engineering.\nFrame connection between new addition and existing structure per approved details.\nInstall all blocking for cabinets, fixtures, and mechanical.\nPass all required framing inspections." },
    { id: "a1_5", label: "Roofing", desc: "Install roof sheathing, underlayment, and ice & water shield at all critical areas.\nInstall roofing material per client selection.\nFlash and seal all roof-to-wall transitions, valleys, and penetrations.\nInstall gutters and downspouts per plan.\nTie new roof into existing roof structure with proper flashing and waterproofing.\nPass all required roofing inspections.", finishKey: "roofing" },
    { id: "a1_6", label: "Windows & Exterior Doors", desc: "Install all new windows per approved plans \u2014 style and material selected by client.\nFlash and weatherproof all window and door openings per manufacturer specs.\nInstall exterior doors including entry, sliding, or French doors as specified.\nInstall all hardware, locks, and weatherstripping.\nPass energy compliance inspections.", finishKey: "windows" },
    { id: "a1_7", label: "Exterior Finish", desc: "Install exterior sheathing, house wrap, and flashing per code.\nInstall exterior finish material per approved plan.\nMatch exterior finish of existing home for seamless transition.\nInstall exterior trim, fascia boards, and soffit vents.\nApply exterior paint or finish coats.", finishKey: "siding" },
    { id: "a1_8", label: "Electrical", desc: "Run all new electrical circuits per approved electrical plan.\nInstall all outlets, switches, dimmers, and dedicated appliance circuits.\nInstall recessed lights, fixture boxes, and exterior lighting.\nInstall smoke detectors, CO detectors, and arc-fault breakers per current code.\nPass all required electrical inspections." },
    { id: "a1_9", label: "Plumbing", desc: "Install new plumbing supply and drain lines per approved plans.\nConnect new plumbing to existing house main lines.\nInstall shut-off valves at all new fixture locations.\nInstall hose bibs and exterior cleanouts as required.\nPass all required plumbing inspections." },
    { id: "a1_10", label: "HVAC", finishKey: "mini_split", desc: "Extend existing HVAC system or install new dedicated unit for the addition.\nInstall all ductwork, supply vents, and return air per mechanical plan.\nPerform Manual J load calculation to ensure proper system sizing.\nInstall new thermostat or zone controller as needed.\nPass all required HVAC inspections." },
    { id: "a1_11", label: "Insulation", finishKey: "insulation_type", desc: "Install wall insulation in all exterior and interior shared per Title 24.\nInstall ceiling/roof insulation per energy code requirements.\nPass all required energy and insulation inspections." },
    { id: "a1_12", label: "Drywall & Paint", finishKey: "drywall_level", finishKey2: "drywall_texture", desc: "Hang drywall on all walls and ceilings throughout the addition.\nTape, mud, sand, and texture all surfaces to match existing or per client selection.\nPrime and apply two coats of premium interior paint throughout.\nPaint all trim, doors, and casings." },
    { id: "a1_13", label: "Flooring", desc: "Install subfloor prep, leveling, and moisture barriers as needed.\nInstall flooring throughout addition.\nInstall baseboards, shoe molding, and transition strips at all thresholds.", finishKey: "flooring" },
    { id: "a1_14", label: "Interior Doors, Trim & Millwork", desc: "Install all interior doors with hardware per client selection.\nInstall baseboards, window casings, and door trim per design.\nInstall closet shelving, rods, and organizer systems.\nFill, caulk, sand, and paint all trim.", finishKey: "doors" },
    { opt: true, id: "add_ka1", label: "Kitchen \u2014 Cabinets", desc: "Install all base and upper cabinets per approved kitchen layout.\nLevel, shim, and secure to wall studs and blocking.\nInstall all hardware \u2014 handles, pulls, knobs, hinges.", finishKey: "cabinets" },
    { opt: true, id: "add_ka2", label: "Kitchen \u2014 Countertops", desc: "Template countertops after cabinets are installed.\nFabricate with specified edge profile.\nInstall with proper support and seams.\nCut sink and cooktop cutouts.", finishKey: "countertops" },
    { opt: true, id: "add_ka3", label: "Kitchen \u2014 Backsplash", desc: "Prep wall surfaces and install backsplash per design.\nGrout, seal, and clean all surfaces.\nInstall edge trim at all exposed edges.", finishKey: "backsplash" },
    { opt: true, id: "add_ka4", label: "Kitchen \u2014 Flooring", desc: "Remove existing kitchen flooring and prep subfloor.\nInstall new kitchen flooring.\nInstall baseboards and transition strips.", finishKey: "flooring" },
    { opt: true, id: "add_ka5", label: "Kitchen \u2014 Plumbing Fixtures", desc: "Install kitchen sink \u2014 undermount, farmhouse, or other per design.\nInstall faucet, sprayer, soap dispenser, and accessories.\nInstall and wire garbage disposal.\nConnect dishwasher drain and supply." },
    { opt: true, id: "add_ka6", label: "Kitchen \u2014 Range Hood & Venting", desc: "Install range hood with ductwork vented to exterior.\nEnsure adequate supply and return air to kitchen." },
    { opt: true, id: "add_ka7", label: "Kitchen \u2014 Appliance Installation", desc: "Receive and install all client-purchased appliances.\nEnsure proper electrical, gas, and plumbing connections.\nVerify all appliances are level, secured, and operational.\nNote: Company will not install high-end appliances \u2014 to be installed by distributor/manufacturer." },
    { opt: true, id: "add_ka8", label: "Kitchen \u2014 Lighting", desc: "Install recessed lights, pendants, and under-cabinet LEDs.\nInstall all switches, dimmers, and smart controls." },
    { opt: true, id: "add_ba1", label: "Bathroom \u2014 Tub/Shower", desc: "Install tub or shower base per design.\nWaterproof all wet areas with membrane system.\nInstall cement board or tile backer on all wet walls.\nBuild bench, curb, and niche per design.\nFlood test to verify waterproofing.", finishKey: "tub_shower" },
    { opt: true, id: "add_ba2", label: "Bathroom \u2014 Tile Work", desc: "Install wall tile in shower/tub surround \u2014 floor to ceiling or per design.\nInstall floor tile with proper slope to drain.\nInstall accent tile and niche tile per design.\nGrout, seal, and clean all surfaces." },
    { opt: true, id: "add_ba3", label: "Bathroom \u2014 Vanity & Countertop", desc: "Install vanity cabinet and countertop.\nInstall undermount or vessel sink per design.\nInstall faucet, drain assembly, and mirror.\nConnect plumbing supply and drain.", finishKey: "vanity" },
    { opt: true, id: "add_ba4", label: "Bathroom \u2014 Shower Glass", desc: "Measure and order frameless or semi-frameless glass enclosure per design.\nInstall glass door and panels with proper hardware and seals.\nAlign, adjust, and silicone all glass components." },
    { opt: true, id: "add_ba5", label: "Bathroom \u2014 Toilet & Fixtures", desc: "Install toilet with wax ring, bolts, and supply line.\nInstall all plumbing trim and escutcheons.\nInstall towel bars, TP holder, robe hooks, and all accessories." },
    { opt: true, id: "add_ba6", label: "Bathroom \u2014 Lighting & Exhaust", desc: "Install vanity light fixture, recessed lights, and accent lighting.\nInstall exhaust fan \u2014 standard or combination fan/light/heater unit.\nInstall all switches, dimmers, and cover plates." },
    { id: "a1_15", label: "Final Clean & Punch List", desc: "Perform thorough final cleaning of all areas.\nConduct walk-through with client to compile punch list.\nComplete all punch list items.\nRemove all construction materials and debris from property." },
  ],

  // ── 2ND STORY ADDITION ──
  addition_2nd: [
    { id: "a2_1", label: "Design, Architectural & Engineering Plans", std: true, desc: "Meet with client to define the second-story addition scope, room types, and design.\nDevelop architectural plans with floor plans, elevations, sections, and roof plan.\nCoordinate structural engineering for new floor framing, load path to foundation, and any required retrofits to existing first-story structure.\nPrepare Title 24 energy calculations and soils report if needed.\nSubmit for permit and assist through plan check process." },
    { id: "a2_2", label: "Existing Roof Removal & Shoring", desc: "Set up temporary weather protection (tarps, temporary roof) before roof removal.\nRemove existing roof framing, sheathing, and roofing materials.\nInstall temporary shoring to support existing first-floor structure during construction.\nProtect interior of existing home from weather during open-roof phase.\nHaul and dump all demolition debris." },
    { id: "a2_3", label: "Foundation & First-Floor Retrofit", desc: "Reinforce existing foundation per structural engineer\u2019s retrofit plan.\nInstall new hold-downs, anchor bolts, and shear transfer hardware at first-floor level.\nSister or reinforce existing first-floor framing members if required to carry second-story loads.\nPour new footings or grade beams if required by engineering.\nPass all required foundation and structural retrofit inspections.", finishKey: "foundation" },
    { id: "a2_4", label: "Second-Floor Framing", desc: "Frame second-floor deck including joists, rim board, and subfloor per structural plan.\nFrame all second-story walls, headers, and openings per architectural plans.\nFrame new roof structure including rafters, ridge, and ceiling joists.\nInstall engineered beams, LVL headers, and steel connections per engineering.\nInstall all hold-down and shear wall hardware.\nFrame staircase opening and install stair stringers per code.\nPass all required framing inspections." },
    { id: "a2_5", label: "Staircase Construction", desc: "Build staircase connecting first and second floors per code \u2014 minimum width, headroom, and tread/riser dimensions.\nInstall stair stringers, treads, and risers.\nInstall handrail and guardrail per code height and baluster spacing requirements.\nFinish staircase with client-selected materials (hardwood treads, painted risers, etc.).\nDrywall, trim, and paint stairwell walls." },
    { id: "a2_6", label: "Roofing", desc: "Install roof sheathing, underlayment, and ice & water shield at all valleys and penetrations.\nInstall new roofing material per client selection.\nFlash and seal all roof-to-wall transitions and penetrations.\nInstall gutters and downspouts per plan.\nPass all required roofing inspections.", finishKey: "roofing" },
    { id: "a2_7", label: "Windows & Exterior Doors", desc: "Install all second-story windows per approved plans \u2014 style and material selected by client.\nFlash and weatherproof all openings per manufacturer specifications.\nInstall any exterior doors (balcony, deck access) as specified.\nPass energy compliance inspections.", finishKey: "windows" },
    { id: "a2_8", label: "Exterior Finish", desc: "Install exterior sheathing, house wrap, and flashing on all new walls.\nApply exterior finish material to match existing first-story exterior.\nInstall fascia, soffit, and trim to match existing home.\nBlend new and existing exterior finishes for a seamless look.", finishKey: "siding" },
    { id: "a2_9", label: "Electrical", desc: "Run all new electrical circuits per approved plans.\nInstall sub-panel on second floor if required.\nInstall all outlets, switches, dimmers, and dedicated circuits.\nInstall lighting, smoke detectors, CO detectors, and arc-fault breakers per code.\nPass all required electrical inspections." },
    { id: "a2_10", label: "Plumbing", desc: "Run new plumbing supply and drain lines for second-floor bathrooms, kitchen, or laundry.\nConnect second-floor plumbing to existing main stack and supply lines.\nInstall shut-off valves at all fixture locations.\nEnsure proper venting per code.\nPass all required plumbing inspections." },
    { id: "a2_11", label: "HVAC", finishKey: "mini_split", desc: "Install dedicated HVAC system or extend existing system to second floor.\nRun ductwork through walls, chases, or floor cavities per mechanical plan.\nInstall supply vents, return air, and thermostat/zone controller.\nPerform load calculation to ensure proper sizing.\nPass all required HVAC inspections." },
    { id: "a2_12", label: "Insulation, Drywall & Paint", finishKey: "insulation_type", finishKey2: "drywall_texture", desc: "Insulate all exterior walls, ceiling/roof, and floor cavities per Title 24.\nHang, tape, mud, and texture all drywall surfaces.\nPrime and apply two coats of paint throughout second floor.\nPaint all trim, doors, and casings.\nMatch finishes at transition between first and second floors." },
    { id: "a2_13", label: "Flooring", desc: "Install subfloor prep, leveling, and sound-deadening underlayment.\nInstall flooring throughout second floor.\nInstall baseboards and transition strips.\nConsider sound transmission between floors (STC rating).", finishKey: "flooring" },
    { id: "a2_14", label: "Interior Doors, Trim & Millwork", desc: "Install all interior doors with hardware per client selection.\nInstall baseboards, crown molding, casings, and trim throughout.\nInstall closet systems and built-ins as specified.\nFill, caulk, sand, and paint all trim.", finishKey: "doors" },
    { opt: true, id: "add_ka1", label: "Kitchen \u2014 Cabinets", desc: "Install all base and upper cabinets per approved kitchen layout.\nLevel, shim, and secure to wall studs and blocking.\nInstall all hardware \u2014 handles, pulls, knobs, hinges.", finishKey: "cabinets" },
    { opt: true, id: "add_ka2", label: "Kitchen \u2014 Countertops", desc: "Template countertops after cabinets are installed.\nFabricate with specified edge profile.\nInstall with proper support and seams.\nCut sink and cooktop cutouts.", finishKey: "countertops" },
    { opt: true, id: "add_ka3", label: "Kitchen \u2014 Backsplash", desc: "Prep wall surfaces and install backsplash per design.\nGrout, seal, and clean all surfaces.\nInstall edge trim at all exposed edges.", finishKey: "backsplash" },
    { opt: true, id: "add_ka4", label: "Kitchen \u2014 Flooring", desc: "Remove existing kitchen flooring and prep subfloor.\nInstall new kitchen flooring.\nInstall baseboards and transition strips.", finishKey: "flooring" },
    { opt: true, id: "add_ka5", label: "Kitchen \u2014 Plumbing Fixtures", desc: "Install kitchen sink \u2014 undermount, farmhouse, or other per design.\nInstall faucet, sprayer, soap dispenser, and accessories.\nInstall and wire garbage disposal.\nConnect dishwasher drain and supply." },
    { opt: true, id: "add_ka6", label: "Kitchen \u2014 Range Hood & Venting", desc: "Install range hood with ductwork vented to exterior.\nEnsure adequate supply and return air to kitchen." },
    { opt: true, id: "add_ka7", label: "Kitchen \u2014 Appliance Installation", desc: "Receive and install all client-purchased appliances.\nEnsure proper electrical, gas, and plumbing connections.\nVerify all appliances are level, secured, and operational.\nNote: Company will not install high-end appliances \u2014 to be installed by distributor/manufacturer." },
    { opt: true, id: "add_ka8", label: "Kitchen \u2014 Lighting", desc: "Install recessed lights, pendants, and under-cabinet LEDs.\nInstall all switches, dimmers, and smart controls." },
    { opt: true, id: "add_ba1", label: "Bathroom \u2014 Tub/Shower", desc: "Install tub or shower base per design.\nWaterproof all wet areas with membrane system.\nInstall cement board or tile backer on all wet walls.\nBuild bench, curb, and niche per design.\nFlood test to verify waterproofing.", finishKey: "tub_shower" },
    { opt: true, id: "add_ba2", label: "Bathroom \u2014 Tile Work", desc: "Install wall tile in shower/tub surround \u2014 floor to ceiling or per design.\nInstall floor tile with proper slope to drain.\nInstall accent tile and niche tile per design.\nGrout, seal, and clean all surfaces." },
    { opt: true, id: "add_ba3", label: "Bathroom \u2014 Vanity & Countertop", desc: "Install vanity cabinet and countertop.\nInstall undermount or vessel sink per design.\nInstall faucet, drain assembly, and mirror.\nConnect plumbing supply and drain.", finishKey: "vanity" },
    { opt: true, id: "add_ba4", label: "Bathroom \u2014 Shower Glass", desc: "Measure and order frameless or semi-frameless glass enclosure per design.\nInstall glass door and panels with proper hardware and seals.\nAlign, adjust, and silicone all glass components." },
    { opt: true, id: "add_ba5", label: "Bathroom \u2014 Toilet & Fixtures", desc: "Install toilet with wax ring, bolts, and supply line.\nInstall all plumbing trim and escutcheons.\nInstall towel bars, TP holder, robe hooks, and all accessories." },
    { opt: true, id: "add_ba6", label: "Bathroom \u2014 Lighting & Exhaust", desc: "Install vanity light fixture, recessed lights, and accent lighting.\nInstall exhaust fan \u2014 standard or combination fan/light/heater unit.\nInstall all switches, dimmers, and cover plates." },
    { id: "a2_15", label: "First-Floor Repairs & Patching", desc: "Repair and patch all first-floor ceilings affected by second-story construction.\nRepair walls, trim, and paint at staircase opening and adjacent areas.\nRestore any first-floor finishes disturbed during construction.\nMatch existing textures and paint throughout." },
    { id: "a2_16", label: "Final Clean & Punch List", desc: "Perform thorough final clean of entire project area.\nConduct detailed walk-through with client.\nComplete all punch list items.\nRemove all debris and materials from property." },
  ],

  // ── ADU / JADU ──
  adu_jadu: [
    { id: "ad1", label: "Design, Architectural & Engineering Plans", std: true, desc: "Consult with client on ADU size, layout, intended use, and design preferences.\nDevelop complete architectural plans including site plan, floor plans, elevations, sections, and details.\nCoordinate structural engineering for foundation, framing, and lateral systems.\nPrepare Title 24 energy calculations, soils report, and any required surveys.\nAssist in permit submission and plan check process through local building department.\nAddress any HOA, zoning, or setback requirements." },
    { id: "ad2", label: "Site Prep & Utilities", desc: "Clear and grade the building site per approved site plan.\nExcavate for foundation per geotechnical engineer\u2019s recommendations.\nTrench and install underground utilities \u2014 sewer lateral, water supply, gas, and electrical conduit.\nConnect to existing main house utilities or install new meters per local utility requirements.\nInstall temporary construction power and water." },
    { id: "ad3", label: "Foundation", desc: "Form and pour foundation per structural engineer\u2019s approved plan.\nInstall all anchor bolts, hold-downs, and embedded connection hardware.\nInstall underslab plumbing rough-in before concrete pour.\nInstall moisture barriers and underslab insulation per code.\nPour slab or stem walls with proper reinforcement.\nPass all required foundation inspections.", finishKey: "foundation" },
    { id: "ad4", label: "Framing", desc: "Frame all exterior and interior walls per approved plans.\nFrame floor system  \u2014 joists, rim board, and subfloor.\nFrame roof structure per architectural plan \u2014 rafters, ridge, and ceiling framing.\nInstall engineered beams, headers, and posts per structural specifications.\nInstall all shear wall, hold-down, and tie-down hardware.\nInstall blocking for cabinets, fixtures, and all mechanical.\nPass all required framing inspections." },
    { id: "ad5", label: "Roofing", desc: "Install roof sheathing, underlayment, and waterproofing at all critical areas.\nInstall roofing material per client selection.\nFlash and seal all penetrations, vents, and roof-to-wall transitions.\nInstall gutters and downspouts per plan.\nPass all required roofing inspections.", finishKey: "roofing" },
    { id: "ad6", label: "Windows & Exterior Doors", desc: "Install all windows per approved plans \u2014 energy-efficient, style per client.\nInstall entry door, sliding glass doors, or French doors per plan.\nFlash and weatherproof all openings per manufacturer specifications.\nInstall all hardware, locks, and weatherstripping.", finishKey: "windows" },
    { id: "ad7", label: "Exterior Finish", desc: "Install sheathing, house wrap, and flashing per code.\nApply exterior finish per approved plan.\nInstall exterior trim, fascia, and soffits.\nApply exterior paint or finish coats.\nRun all circuits per approved electrical plan.\nInstall all outlets, switches, dimmers, GFCI, and AFCI per code.\nInstall recessed lights, exterior fixtures, and all specified lighting.\nInstall smoke detectors, CO detectors, and doorbell.\nPass all required electrical inspections." },
    { id: "ad9", label: "Plumbing", desc: "Install complete plumbing system \u2014 supply, drain, waste, and vent.\nRough-in for kitchen, bathroom(s), and laundry as specified.\nInstall water heater \u2014 tankless or standard per client selection.\nInstall all shut-off valves, cleanouts, and hose bibs.\nPass all required plumbing inspections." },
    { id: "ad10", label: "HVAC", finishKey: "mini_split", desc: "Install dedicated HVAC system for the ADU \u2014 mini-split, central, or hybrid per design.\nInstall all ductwork, supply vents, and return air per mechanical plan.\nInstall thermostat and zone controls.\nEnsure system is properly sized per Manual J load calculation.\nPass all required HVAC inspections." },
    { id: "ad11", label: "Insulation", finishKey: "insulation_type", desc: "Install insulation in all exterior walls, ceiling/roof, and floor per Title 24.\nInstall vapor barriers and air sealing per energy code.\nInsulate all plumbing pipes in exterior walls.\nPass all required energy and insulation inspections." },
    { id: "ad12", label: "Drywall & Paint", finishKey: "drywall_level", finishKey2: "drywall_texture", desc: "Hang drywall on all walls and ceilings throughout the ADU.\nTape, mud, sand, and texture all surfaces per client preference.\nPrime and apply two coats of premium interior paint throughout.\nPaint all trim, doors, and casings.\nApply paint or finish to all interior and exterior surfaces." },
    { id: "ad13", label: "Kitchen Build-Out", desc: "Install cabinets \u2014 base and upper per approved kitchen layout.\nInstall countertops.\nInstall kitchen sink, faucet, and garbage disposal.\nConnect dishwasher, range, microwave, and refrigerator.\nInstall backsplash tile per design.\nNote: Appliances are owner-supplied unless otherwise agreed.", finishKey: "countertops" },
    { id: "ad14", label: "Bathroom Build-Out", desc: "Install vanity, countertop, and mirror.\nInstall shower/tub \u2014 type per client selection.\nWaterproof all wet areas and install tile per design.\nInstall toilet and all plumbing trim.\nInstall exhaust fan, lighting, and accessories.", finishKey: "tub_shower" },
    { id: "ad15", label: "Flooring", desc: "Install flooring throughout ADU.\nInstall baseboards, shoe molding, and transition strips.\nPrep subfloor including leveling and moisture barriers as needed.", finishKey: "flooring" },
    { id: "ad16", label: "Interior Doors, Trim & Closets", desc: "Install all interior doors with hardware per client selection.\nInstall baseboards, window casings, and door trim.\nBuild and install closet shelving systems.\nFill, caulk, sand, and paint all trim.", finishKey: "doors" },
    { opt: true, id: "adu_ka1", label: "Kitchen \u2014 Cabinets", desc: "Install all base and upper cabinets per approved kitchen layout.\nLevel, shim, and secure to wall studs and blocking.\nInstall all hardware \u2014 handles, pulls, knobs, hinges.", finishKey: "cabinets" },
    { opt: true, id: "adu_ka2", label: "Kitchen \u2014 Countertops", desc: "Template countertops after cabinets are installed.\nFabricate with specified edge profile.\nInstall with proper support and seams.\nCut sink and cooktop cutouts.", finishKey: "countertops" },
    { opt: true, id: "adu_ka3", label: "Kitchen \u2014 Backsplash", desc: "Prep wall surfaces and install backsplash per design.\nGrout, seal, and clean all surfaces.\nInstall edge trim at all exposed edges.", finishKey: "backsplash" },
    { opt: true, id: "adu_ka4", label: "Kitchen \u2014 Flooring", desc: "Remove existing kitchen flooring and prep subfloor.\nInstall new kitchen flooring.\nInstall baseboards and transition strips.", finishKey: "flooring" },
    { opt: true, id: "adu_ka5", label: "Kitchen \u2014 Plumbing Fixtures", desc: "Install kitchen sink \u2014 undermount, farmhouse, or other per design.\nInstall faucet, sprayer, soap dispenser, and accessories.\nInstall and wire garbage disposal.\nConnect dishwasher drain and supply." },
    { opt: true, id: "adu_ka6", label: "Kitchen \u2014 Range Hood & Venting", desc: "Install range hood with ductwork vented to exterior.\nEnsure adequate supply and return air to kitchen." },
    { opt: true, id: "adu_ka7", label: "Appliance Installation", desc: "Receive and install all client-purchased appliances.\nEnsure proper electrical, gas, and plumbing connections.\nVerify all appliances are level, secured, and operational.\nNote: Company will not install high-end appliances \u2014 to be installed by distributor/manufacturer." },
    { opt: true, id: "adu_ka8", label: "Lighting", desc: "Install recessed lights, pendants, and under-cabinet LEDs.\nInstall all switches, dimmers, and smart controls." },
    { opt: true, id: "adu_ba1", label: "Bathroom \u2014 Tub/Shower", desc: "Install tub or shower base per design.\nWaterproof all wet areas with membrane system.\nInstall cement board or tile backer on all wet walls.\nBuild bench, curb, and niche per design.\nFlood test to verify waterproofing.", finishKey: "tub_shower" },
    { opt: true, id: "adu_ba2", label: "Bathroom \u2014 Tile Work", desc: "Install wall tile in shower/tub surround \u2014 floor to ceiling or per design.\nInstall floor tile with proper slope to drain.\nInstall accent tile and niche tile per design.\nGrout, seal, and clean all surfaces." },
    { opt: true, id: "adu_ba3", label: "Bathroom \u2014 Vanity & Countertop", desc: "Install vanity cabinet and countertop.\nInstall undermount or vessel sink per design.\nInstall faucet, drain assembly, and mirror.\nConnect plumbing supply and drain.", finishKey: "vanity" },
    { opt: true, id: "adu_ba4", label: "Bathroom \u2014 Shower Glass", desc: "Measure and order frameless or semi-frameless glass enclosure per design.\nInstall glass door and panels with proper hardware and seals.\nAlign, adjust, and silicone all glass components." },
    { opt: true, id: "adu_ba5", label: "Bathroom \u2014 Toilet & Fixtures", desc: "Install toilet with wax ring, bolts, and supply line.\nInstall all plumbing trim and escutcheons.\nInstall towel bars, TP holder, robe hooks, and all accessories." },
    { opt: true, id: "adu_ba6", label: "Bathroom \u2014 Lighting & Exhaust", desc: "Install vanity light fixture, recessed lights, and accent lighting.\nInstall exhaust fan \u2014 standard or combination fan/light/heater unit.\nInstall all switches, dimmers, and cover plates." },
    { id: "ad18", label: "Final Clean & Punch List", desc: "Perform thorough final clean of entire ADU.\nConduct walk-through with client and compile punch list.\nComplete all items.\nRemove all construction materials and debris." },
  ],

  // ── GARAGE CONVERSION ──
  garage_conv: [
    { id: "gc1", label: "Design, Architectural & Engineering Plans", std: true, desc: "Conduct multiple in-depth meetings with the client to fully understand their design preferences, lifestyle needs, and aesthetic goals for the converted space.\nDevelop detailed architectural plans including floor plans, elevations, sections, and construction documents.\nCoordinate with structural engineer to evaluate existing garage structure and determine required reinforcements.\nPrepare Title 24 energy calculations and any required reports.\nAssist in the permit acquisition process through the local building department.\nAddress any HOA, zoning, or setback requirements related to the conversion." },
    { id: "gc2", label: "Demolition & Prep", desc: "Protect all surfaces, fixtures, and finishes outside the work area with coverings and dust barriers.\nRemove garage door, tracks, opener, and all associated hardware.\nRemove any existing interior partitions, shelving, and storage systems.\nRemove existing concrete slab coatings, epoxy, or finishes if needed.\nCap and protect all existing electrical, plumbing, and gas lines during demolition.\nHaul and dump all debris and trash throughout the duration of the project.\nMaintain a clean and safe work environment at all times." },
    { id: "gc3", label: "Foundation & Slab Work", desc: "Evaluate existing garage slab for structural adequacy per engineer\u2019s assessment.\nSaw-cut and remove slab sections as needed for new plumbing rough-in.\nRaise or level slab to match main house floor height if required \u2014 pour leveling compound or new concrete as specified.\nInstall moisture barrier and underslab insulation per Title 24 energy code.\nRepair or reinforce foundation stem walls and footings per structural engineer\u2019s plan.\nPass all required foundation inspections.", finishKey: "foundation" },
    { id: "gc4", label: "Framing & Wall Infill", desc: "Frame new exterior wall where garage door opening was removed \u2014 install bottom plate, studs, top plate, and headers per structural plan.\nInstall sheathing, house wrap, and flashing on new infill wall per code.\nFrame any new interior partition walls, hallways, and door openings per approved architectural plans.\nFrame new closets, niches, and built-in areas as specified.\nInstall blocking for cabinets, handrails, TV mounts, shower glass, and other wall-mounted fixtures.\nInstall all shear wall, hold-down, and tie-down hardware per structural specifications.\nPass all required framing inspections to ensure compliance with building codes." },
    { id: "gc5", label: "Electrical \u2014 Rough", desc: "Run all new electrical circuits, outlets, and switch locations per approved plans.\nInstall dedicated circuits for appliances, HVAC, and other high-draw equipment.\nInstall all junction boxes, conduit, and wiring for recessed lighting, pendant pre-wires, under-cabinet lighting, and decorative fixture boxes.\nInstall wiring for smoke detectors, CO detectors, and doorbell per code.\nPass all required rough electrical inspections." },
    { id: "gc6", label: "Electrical \u2014 Finish", desc: "Install all switches, dimmers, outlets, GFCI, AFCI, and cover plates per code.\nInstall recessed lighting, pendant fixtures, under-cabinet LED lighting, and all decorative fixtures.\nInstall smoke detectors and CO detectors per code requirements.\nProgram and test all dimmers and smart switches if applicable.\nTest all circuits and verify proper operation.\nPass all required final electrical inspections." },
    { id: "gc7", label: "Plumbing \u2014 Rough", desc: "Rough-in all new plumbing supply and drain lines per approved plans.\nSaw-cut existing slab and trench for new drain lines if required.\nInstall supply and drain lines for bathroom (toilet, vanity, shower/tub), kitchenette (sink, dishwasher), and laundry as specified.\nInstall shut-off valves at all new fixture locations.\nInstall water heater supply lines and gas connection if specified.\nConnect to existing house plumbing system with proper transitions.\nPass all required rough plumbing inspections." },
    { id: "gc8", label: "Plumbing \u2014 Finish", desc: "Install all plumbing fixtures \u2014 sinks, faucets, toilets, shower/tub units per client selection.\nInstall garbage disposal and dishwasher connections if applicable.\nConnect and test all fixtures including supply lines and drain connections.\nInstall all plumbing trim, escutcheons, and accessories.\nInstall shower valve trim, diverter, and shower head per client selection.\nTest all connections for leaks and verify proper water pressure and drainage.\nPass all required final plumbing inspections." },
    { id: "gc9", label: "HVAC / Mini Split", finishKey: "mini_split", desc: "Install mini split system(s) for supplemental or primary heating and cooling per mechanical plan.\nAlternatively, extend existing central HVAC system with new ductwork, supply vents, and return air.\nInstall thermostat and zone controls for the converted space.\nEnsure system is properly sized per Manual J load calculation for the new living area.\nInstall condensate drain line and refrigerant lines per manufacturer specifications.\nPass all required HVAC and mechanical inspections." },
    { id: "gc10", label: "Insulation", desc: "Install insulation in all exterior walls \u2014 including new garage door infill wall \u2014 per Title 24 energy requirements.\nInsulate ceiling cavities between garage and any space above per code.\nInstall insulation in floor system if raised above slab.\nInstall vapor barriers and air sealing per energy code.\nInsulate all plumbing pipes in exterior walls to prevent freezing.\nPass all required insulation and energy inspections.", finishKey: "insulation_type" },
    { id: "gc11", label: "Drywall, Tape, Mud & Texture", finishKey: "drywall_level", finishKey2: "drywall_texture", desc: "Hang drywall on all new and existing garage walls and ceilings throughout the converted space.\nUse moisture-resistant drywall (green board or purple board) in all wet areas \u2014 bathroom, kitchenette.\nTape, mud, and sand all joints and seams to specified finish level.\nApply texture to match existing home finishes or per client selection (smooth, knockdown, orange peel, etc.).\nPrepare all surfaces for primer and paint." },
    { id: "gc12", label: "Flooring", desc: "Remove existing garage floor coatings and prep concrete slab for new flooring material.\nInstall moisture barrier and leveling compound as needed for proper subfloor preparation.\nInstall new flooring throughout converted space.\nInstall baseboards, shoe molding, and transition strips at all doorways and material changes.\nEnsure proper expansion gaps and smooth transitions to existing home flooring.", finishKey: "flooring" },
    { id: "gc13", label: "Interior Paint", desc: "Prep all surfaces including patching, sanding, caulking, and priming as needed.\nApply two coats of premium interior paint (limewash, Venetian plaster, Roman clay, etc.) to all walls and ceilings.\nPaint all new trim, doors, and casings to match client\u2019s selected color scheme.\nProtect all flooring, fixtures, and finished surfaces during painting.\nTouch up and final clean after completion.", finishKey: "specialty_paint" },
    { id: "gc14", label: "Interior Doors, Trim & Closets", desc: "Install new interior doors per plan \u2014 style and material selected by client.\nInstall all door hardware including handles, hinges, and stops.\nApply trim and casing around all new door openings to match existing or new trim profile.\nInstall baseboards and window casings per design plan.\nBuild and install closet shelving systems, rods, and organizer components.\nFill all nail holes, caulk joints, and sand smooth before paint.\nAdjust and align all doors for proper fit and operation.", finishKey: "doors" },
    { id: "gc15", label: "Windows & Exterior Finish", desc: "Install new windows to meet egress, light, and ventilation requirements per code.\nInstall energy-efficient windows \u2014 style and material per client selection.\nFlash, seal, and weatherproof all window openings per manufacturer specifications.\nInstall interior and exterior trim and casing around all windows.\nApply exterior finish to new infill wall to match existing home exterior.\nInstall exterior trim, flashing, and paint to blend seamlessly with main house.", finishKey: "windows" },
    { opt: true, id: "gc17", label: "Roof Tear-Off & Demo", desc: "Set up temporary weather protection before roof removal.\nRemove all existing roofing material down to the roof deck.\nInspect roof deck/sheathing for rot, damage, or deterioration.\nReplace any damaged plywood or OSB sheathing with new material.\nHaul and dump all old roofing materials." },
    { opt: true, id: "gc18", label: "Roof Deck Inspection & Repair", desc: "Inspect entire roof deck for rot, soft spots, and structural damage.\nReplace any rotted or damaged plywood/OSB sheathing.\nRe-nail or re-secure any loose sheathing to rafters.\nInstall additional blocking or framing reinforcement where needed.\nEnsure entire roof deck is solid and ready for new roofing." },
    { opt: true, id: "gc19", label: "New Roof Installation", desc: "Install synthetic underlayment over entire roof deck.\nInstall ice & water shield at critical areas per code.\nInstall new roofing material per approved plan.\nInstall starter course, field material, and ridge cap.\nFlash all roof-to-wall transitions, valleys, and penetrations.\nInstall drip edge, ridge vent, gutters, and downspouts.\nPerform magnetic nail sweep and clean-up.", finishKey: "roofing" },
    { std: true, id: "gar_ka1", label: "Kitchen \u2014 Cabinets", desc: "Install all base and upper cabinets per approved kitchen layout.\nLevel, shim, and secure to wall studs and blocking.\nInstall all hardware \u2014 handles, pulls, knobs, hinges.", finishKey: "cabinets" },
    { std: true, id: "gar_ka2", label: "Kitchen \u2014 Countertops", desc: "Template countertops after cabinets are installed.\nFabricate with specified edge profile.\nInstall with proper support and seams.\nCut sink and cooktop cutouts.", finishKey: "countertops" },
    { std: true, id: "gar_ka3", label: "Kitchen \u2014 Backsplash", desc: "Prep wall surfaces and install backsplash per design.\nGrout, seal, and clean all surfaces.\nInstall edge trim at all exposed edges.", finishKey: "backsplash" },
    { std: true, id: "gar_ka4", label: "Kitchen \u2014 Flooring", desc: "Remove existing kitchen flooring and prep subfloor.\nInstall new kitchen flooring.\nInstall baseboards and transition strips.", finishKey: "flooring" },
    { std: true, id: "gar_ka5", label: "Kitchen \u2014 Plumbing Fixtures", desc: "Install kitchen sink \u2014 undermount, farmhouse, or other per design.\nInstall faucet, sprayer, soap dispenser, and accessories.\nInstall and wire garbage disposal.\nConnect dishwasher drain and supply." },
    { std: true, id: "gar_ka6", label: "Kitchen \u2014 Range Hood & Venting", desc: "Install range hood with ductwork vented to exterior.\nEnsure adequate supply and return air to kitchen." },
    { std: true, id: "gar_ka7", label: "Kitchen \u2014 Appliance Installation", desc: "Receive and install all client-purchased appliances.\nEnsure proper electrical, gas, and plumbing connections.\nVerify all appliances are level, secured, and operational.\nNote: Company will not install high-end appliances \u2014 to be installed by distributor/manufacturer." },
    { std: true, id: "gar_ka8", label: "Kitchen \u2014 Lighting", desc: "Install recessed lights, pendants, and under-cabinet LEDs.\nInstall all switches, dimmers, and smart controls." },
    { std: true, id: "gar_ba1", label: "Bathroom \u2014 Tub/Shower", desc: "Install tub or shower base per design.\nWaterproof all wet areas with membrane system.\nInstall cement board or tile backer on all wet walls.\nBuild bench, curb, and niche per design.\nFlood test to verify waterproofing.", finishKey: "tub_shower" },
    { std: true, id: "gar_ba2", label: "Bathroom \u2014 Tile Work", desc: "Install wall tile in shower/tub surround \u2014 floor to ceiling or per design.\nInstall floor tile with proper slope to drain.\nInstall accent tile and niche tile per design.\nGrout, seal, and clean all surfaces." },
    { std: true, id: "gar_ba3", label: "Bathroom \u2014 Vanity & Countertop", desc: "Install vanity cabinet and countertop.\nInstall undermount or vessel sink per design.\nInstall faucet, drain assembly, and mirror.\nConnect plumbing supply and drain.", finishKey: "vanity" },
    { std: true, id: "gar_ba4", label: "Bathroom \u2014 Shower Glass", desc: "Measure and order frameless or semi-frameless glass enclosure per design.\nInstall glass door and panels with proper hardware and seals.\nAlign, adjust, and silicone all glass components." },
    { std: true, id: "gar_ba5", label: "Bathroom \u2014 Toilet & Fixtures", desc: "Install toilet with wax ring, bolts, and supply line.\nInstall all plumbing trim and escutcheons.\nInstall towel bars, TP holder, robe hooks, and all accessories." },
    { std: true, id: "gar_ba6", label: "Bathroom \u2014 Lighting & Exhaust", desc: "Install vanity light fixture, recessed lights, and accent lighting.\nInstall exhaust fan \u2014 standard or combination fan/light/heater unit.\nInstall all switches, dimmers, and cover plates." },
    { id: "gc16", label: "Final Clean & Punch List", desc: "Perform thorough final cleaning of all work areas including dusting, vacuuming, and wiping all surfaces.\nConduct detailed walk-through with client to identify any remaining punch list items.\nComplete all punch list items.\nRemove all construction materials, tools, and debris from the property." },
  ],

  // ── ROOFING ──
  roofing: [
    { id: "r1", label: "Roof Inspection & Assessment", desc: "Perform thorough inspection of existing roof condition, decking, and flashing.\nIdentify any areas of rot, water damage, or structural concerns.\nDocument findings and provide recommendation for repair vs. full replacement.\nTake measurements and calculate material quantities." },
    { id: "r2", label: "Tear-Off Existing Roof", desc: "Remove all existing roofing material down to the roof deck.\nInspect roof deck/sheathing for rot, damage, or deterioration.\nReplace any damaged sheathing or decking with new plywood or OSB.\nHaul and dump all old roofing materials.\nInstall protective tarps and barriers during tear-off." },
    { id: "r3", label: "Roof Deck Repair & Prep", desc: "Replace any rotted or damaged plywood/OSB sheathing.\nRe-nail or re-secure any loose sheathing to rafters.\nInstall additional blocking or framing reinforcement where needed.\nEnsure entire roof deck is solid, level, and ready for new roofing." },
    { id: "r4", label: "Underlayment & Waterproofing", desc: "Install synthetic underlayment over entire roof deck per manufacturer specifications.\nInstall ice & water shield at critical areas per code.\nFlash all roof-to-wall transitions with step and counter flashing.\nSeal all vent pipes, skylights, and other roof penetrations." },
    { id: "r5", label: "Roofing Material Installation", desc: "Install new roofing material per manufacturer specifications and warranty requirements.\nInstall starter course, field shingles/tiles, and ridge cap.\nInstall all hip and ridge details per material specifications.\nMaintain proper exposure, alignment, and fastening pattern throughout.\nInstall all manufacturer-required components for warranty compliance.", finishKey: "roofing" },
    { id: "r6", label: "Flashing & Details", desc: "Install new drip edge at all eaves and rakes.\nInstall or replace all pipe jack boots and vent flashings.\nFlash and seal all skylights, chimneys, and wall transitions.\nInstall valley flashing \u2014 metal or woven per specification.\nSeal all penetrations with roofing-grade sealant." },
    { id: "r7", label: "Ventilation", desc: "Install ridge vent or roof vents per code requirements for proper attic ventilation.\nInstall soffit vents or intake vents to ensure balanced airflow.\nVerify net free area meets code minimum for attic space.\nRemove or seal any existing vents that are no longer needed." },
    { id: "r8", label: "Gutters & Downspouts", desc: "Install new seamless aluminum gutters at all eaves per plan.\nInstall downspouts and route to appropriate drainage areas.\nInstall gutter guards/screens if specified by client.\nEnsure proper slope for water flow and secure attachment to fascia." },
    { id: "r9", label: "Final Inspection & Clean-Up", desc: "Perform thorough ground and roof clean-up including magnetic nail sweep.\nInspect entire roof for proper installation, alignment, and sealing.\nDocument completed work with photos for warranty registration.\nRegister manufacturer warranty and provide documentation to client.\nPass any required building inspections." },
  ],

  // ── EXTERIOR / SIDING ──
  exterior_siding: [
    { id: "es1", label: "Assessment & Prep", desc: "Inspect existing exterior surfaces for damage, rot, and moisture intrusion.\nIdentify areas requiring structural repair before new finish is applied.\nDocument all findings and develop scope of repair work.\nSet up scaffolding, ladders, and fall protection as needed.\nProtect landscaping, windows, and adjacent surfaces." },
    { id: "es2", label: "Removal of Existing Siding/Stucco", desc: "Remove existing siding, stucco, or exterior finish material as required.\nInspect underlying sheathing and framing for damage.\nReplace any rotted or damaged sheathing and framing members.\nHaul and dispose of all removed materials." },
    { id: "es3", label: "Sheathing & Weather Barrier", desc: "Install or repair exterior sheathing (plywood or OSB) as needed.\nInstall house wrap or building paper per code and manufacturer specs.\nInstall flashing at all windows, doors, and wall-to-roof transitions.\nEnsure continuous weather barrier with proper lapping and sealing." },
    { id: "es4", label: "Siding / Exterior Finish Installation", desc: "Install new exterior finish material per manufacturer specifications.\nMaintain proper fastening, spacing, and alignment throughout.\nInstall all corner trim, J-channel, and transition pieces.\nCaulk and seal all joints, seams, and penetrations.\nMatch existing areas where partial replacement is performed.", finishKey: "siding" },
    { id: "es5", label: "Exterior Trim & Details", desc: "Install or replace fascia boards, soffit panels, and frieze boards.\nInstall window and door trim per design.\nInstall architectural details \u2014 shutters, corbels, brackets per plan.\nFill, caulk, and prep all trim for paint." },
    { id: "es6", label: "Exterior Paint / Finish", desc: "Power wash all surfaces to remove dirt, mildew, and loose paint.\nScrape, sand, and prep all surfaces for paint.\nApply primer to all new and bare surfaces.\nApply two coats of premium exterior paint per manufacturer recommendations.\nPaint trim, fascia, soffits, doors, and accent colors per client selection." },
    { id: "es7", label: "Final Clean & Inspection", desc: "Remove all scaffolding, ladders, and equipment.\nClean all windows, surfaces, and surrounding areas.\nRestore landscaping and remove all debris.\nConduct final walk-through with client.\nComplete punch list items." },
  ],

  // ── FLOORING ──
  flooring: [
    { id: "fl1", label: "Floor Assessment & Prep", desc: "Inspect existing flooring and subfloor condition throughout scope areas.\nIdentify any subfloor damage, unevenness, or moisture issues.\nRemove existing flooring material as needed.\nRepair, level, and prep subfloor for new installation.\nInstall moisture barriers and underlayment per flooring manufacturer requirements." },
    { id: "fl2", label: "Flooring Installation", desc: "Install new flooring material per manufacturer specifications and industry standards.\nMaintain proper expansion gaps at all walls and fixed objects.\nStagger joints and maintain consistent pattern throughout.\nInstall transitions at all doorways, material changes, and thresholds.\nClean and inspect all installed flooring.", finishKey: "flooring" },
    { id: "fl3", label: "Baseboards & Trim", desc: "Remove existing baseboards if being replaced.\nInstall new baseboards throughout all floored areas.\nInstall shoe molding at floor-to-baseboard junction if specified.\nFill nail holes, caulk top edge, and paint baseboards.\nInstall transition strips and reducer profiles at all material changes." },
    { id: "fl4", label: "Stair Treads & Risers", desc: "Remove existing stair covering if applicable.\nInstall new stair treads and risers.\nInstall stair nosing and edge profiles per code.\nEnsure consistent tread depth and riser height throughout.\nFinish and seal all stair surfaces." },
    { id: "fl5", label: "Hardwood Refinishing (If Restoring)", desc: "Sand existing hardwood floors using progressive grit sequence.\nFill any gaps, cracks, or nail holes with matching wood filler.\nApply stain per client-selected color (if not going natural).\nApply three coats of polyurethane finish \u2014 oil or water-based per client preference.\nAllow proper cure time between coats and before furniture placement." },
    { id: "fl6", label: "Final Clean & Protection", desc: "Perform thorough cleaning of all new flooring surfaces.\nInstall temporary floor protection in high-traffic areas if other work continues.\nConduct walk-through with client to verify satisfaction.\nProvide care and maintenance instructions for installed flooring." },
  ],

  // ── PAINTING ──
  painting: [
    { id: "pt1", label: "Interior Painting / Specialty Finish \u2014 Walls & Ceilings", desc: "Prep all surfaces \u2014 fill holes, patch cracks, sand rough areas, and caulk gaps.\nApply primer to all new drywall, patched areas, and stain-blocking as needed.\nApply two coats of premium interior paint (limewash, Venetian plaster, Roman clay, microcement) to all walls per client selection.\nPaint ceilings with flat ceiling paint \u2014 white or custom color per client.\nProtect all floors, fixtures, and finished surfaces throughout.", finishKey: "specialty_paint" },
    { id: "pt2", label: "Interior Painting \u2014 Trim, Doors & Casings", desc: "Prep all trim surfaces \u2014 sand, fill holes, and caulk joints.\nApply primer to all bare or previously unpainted trim.\nApply two coats of semi-gloss or satin paint to all baseboards, crown, and casings.\nPaint all interior doors (both sides) and door frames.\nPaint window sills and casings." },
    { id: "pt3", label: "Cabinet Painting / Refinishing", desc: "Remove all cabinet doors, drawers, and hardware.\nClean, sand, and degloss all surfaces.\nApply bonding primer formulated for cabinets.\nApply two coats of cabinet-grade paint or lacquer finish.\nReinstall all doors, drawers, and hardware.\nAdjust all hinges for proper alignment." },
    { id: "pt4", label: "Exterior Painting \u2014 Siding & Body", desc: "Power wash all exterior surfaces to remove dirt, mildew, and loose paint.\nScrape and sand all peeling or flaking areas.\nCaulk all gaps, cracks, and joints.\nApply primer to all bare wood and problem areas.\nApply two coats of premium exterior paint to all siding and body surfaces." },
    { id: "pt5", label: "Exterior Painting \u2014 Trim & Details", desc: "Prep all exterior trim \u2014 fascia, soffits, window frames, door frames, and railings.\nApply primer to all bare or problem areas.\nApply two coats of exterior trim paint in client\u2019s accent color selections.\nPaint garage door(s) and exterior shutters if applicable.\nPaint any architectural details \u2014 corbels, brackets, columns." },
    { id: "pt6", label: "Exterior Painting \u2014 Stucco", desc: "Power wash and clean all stucco surfaces.\nRepair any cracks, holes, or damaged areas with matching stucco patch.\nApply masonry primer to all surfaces.\nApply two coats of elastomeric or premium exterior paint to all stucco.\nEnsure even coverage and consistent finish." },
    { id: "pt7", label: "Final Touch-Up & Clean", desc: "Perform detailed inspection of all painted surfaces.\nTouch up any missed spots, drips, or imperfections.\nRemove all tape, drop cloths, and protective coverings.\nClean all windows, fixtures, and hardware of any paint residue.\nConduct walk-through with client to verify satisfaction." },
  ],

  // ── WINDOWS & DOORS ──
  windows_doors: [
    { id: "wd1", label: "Window Replacement", desc: "Remove existing windows and inspect rough openings for damage.\nRepair framing, sills, or headers as needed.\nInstall new energy-efficient windows \u2014 style and material per client selection.\nFlash and weatherproof all openings per manufacturer and code requirements.\nInstall interior and exterior trim and casing.\nTest all windows for smooth operation and proper locking.\nPass energy compliance inspections.", finishKey: "windows" },
    { id: "wd2", label: "Exterior Door Replacement", desc: "Remove existing exterior door(s) and inspect rough opening and threshold.\nRepair framing and subfloor at threshold if needed.\nInstall new exterior door \u2014 style and material per client selection.\nInstall weatherstripping, threshold, and hardware including deadbolt and handle set.\nFlash and seal exterior of door opening.\nVerify proper operation, alignment, and weather seal.", finishKey: "doors" },
    { id: "wd3", label: "Sliding Glass / French Door Installation", desc: "Remove existing door or prepare new opening per approved plans.\nInstall header and support framing if new opening is being created.\nInstall sliding glass door or French door unit \u2014 style per client selection.\nInstall sill pan flashing, weatherproofing, and exterior trim.\nInstall interior casing and hardware.\nVerify smooth operation and locking function." },
    { id: "wd4", label: "Interior Door Replacement", desc: "Remove existing interior doors and hardware.\nInstall new interior doors \u2014 style per client selection.\nInstall new hinges, handle sets, and door stops.\nInstall or replace door casings and trim.\nAdjust all doors for proper swing, latch, and clearance.", finishKey: "doors" },
    { id: "wd5", label: "Trim & Casing", desc: "Install or replace window and door casings in client-selected profile.\nInstall exterior trim and brick mold as needed.\nFill, caulk, and paint all trim to match.\nEnsure consistent profile and finish throughout." },
  ],

  // ── DECK / PATIO ──
  deck_patio: [
    { id: "dp1", label: "Design & Permits", desc: "Consult with client on deck/patio size, layout, and intended use.\nPrepare deck plans including framing, footings, railing, and stairs per code.\nSubmit for permit if required by scope and local jurisdiction.\nVerify setback requirements and property line clearances." },
    { id: "dp2", label: "Site Prep & Footings", desc: "Clear and excavate deck footprint per approved plan.\nDig and pour concrete pier footings per structural requirements.\nInstall post bases and connection hardware.\nEnsure all footings are level, plumb, and at proper depth.\nPass foundation/footing inspection if required." },
    { id: "dp3", label: "Framing & Structure", desc: "Install ledger board to house with proper flashing and lag bolts.\nInstall posts, beams, and joists per approved framing plan.\nInstall joist hangers, blocking, and all structural hardware.\nEnsure proper spacing, cantilever limits, and bearing per code.\nInstall substructure for stairs and landing if applicable.\nPass framing inspection if required." },
    { id: "dp4", label: "Decking Installation", desc: "Install decking material per manufacturer specifications.\nMaintain proper gapping, fastener pattern, and board alignment.\nInstall picture frame border or inlay pattern if specified.\nInstall stair treads and risers.\nClean and inspect all surfaces after installation.", finishKey: "deck" },
    { id: "dp5", label: "Railing & Stairs", desc: "Install guardrails at required height per code \u2014 36\" for residential decks under 30\" elevation, 42\" for higher.\nInstall balusters with proper spacing \u2014 maximum 4\" between balusters per code.\nInstall handrails on all stairways per code.\nInstall post caps and decorative elements per client selection.\nVerify all railings are solid and meet code requirements." },
    { id: "dp6", label: "Electrical & Lighting", desc: "Install exterior-rated outlets (GFCI protected) if specified.\nInstall deck post lights, step lights, or under-rail lighting.\nInstall low-voltage landscape lighting around deck area.\nAll electrical work per code with proper weatherproof covers." },
    { id: "dp7", label: "Concrete Patio (If Applicable)", desc: "Excavate and grade patio area per plan.\nInstall compacted base material and forms.\nPour concrete with proper thickness, reinforcement, and slope for drainage.\nApply finish \u2014 broom, stamped, exposed aggregate, or smooth per client selection.\nCut control joints and apply sealer." },
    { id: "dp8", label: "Final Clean & Inspection", desc: "Clean all deck/patio surfaces and surrounding areas.\nRemove all construction debris and materials.\nConduct walk-through with client.\nProvide maintenance instructions for decking material." },
  ],

  // ── SUNROOM (KIT / PREFAB INSTALL) ──
  sunroom: [
    { id: "sr0", label: "Demo Existing Structure", desc: "Remove existing sunroom, patio enclosure, or screen room structure in its entirety.\nDemo and haul away all framing, glass panels, aluminum components, roofing, and hardware.\nProtect adjacent exterior wall and existing slab/foundation during demolition.\nPatch and prep exterior wall where structure was attached." },
    { id: "sr1", label: "Site Prep & Slab", desc: "Assess existing concrete slab/patio for levelness and structural condition.\nIf slab is damaged, cracked, or uneven: saw-cut, remove, and pour new reinforced concrete slab to accommodate sunroom footprint.\nIf existing slab is in good condition, prep surface and proceed with kit installation." },
    { id: "sr2", label: "Sunroom Kit Assembly & Installation", desc: "Supply and install prefab sunroom system (model and style TBD with client).\nAssemble all framing, panel tracks, and structural components per specifications.\nAnchor and secure frame to existing structure and slab." },
    { id: "sr3", label: "Windows & Door Panels", desc: "Install all glass panel assemblies included in kit.\nInstall designated door unit(s) \u2014 swing or sliding per kit design.\nVerify all panels are plumb, square, and properly sealed.\nApply weatherstripping and perimeter caulking throughout." },
    { id: "sr4", label: "Electrical", desc: "Run dedicated circuit from main panel to sunroom.\nInstall recessed or surface lighting (quantity TBD).\nInstall outlets per code (minimum 1 per wall).\nInstall switch and cover plates.\nAll work to be permitted and inspected per local code." },
    { id: "sr5", label: "Gutters & Drainage", desc: "Install gutters along sunroom roofline to match or complement existing home gutters.\nConnect downspouts and direct drainage away from foundation." },
    { id: "sr6", label: "Flooring", desc: "Remove any existing deteriorated surface material as needed.\nSupply and install flooring throughout sunroom (material TBD \u2014 tile, LVP, or other per client selection).\nInclude transition strip at entry threshold." },
    { id: "sr7", label: "Final Clean & Punch", desc: "Daily job site cleanup throughout installation.\nHaul and dispose of all debris and packaging.\nFinal walkthrough and punch list with client prior to closeout." },
  ],
} as const;

// ============================================================
// PROJECT TYPE TO SCOPE CATEGORY MAPPING
// ============================================================

export const PROJECT_TYPE_TO_SCOPE: Record<string, string[]> = {
  interior_remodel: ["drywall_plaster", "flooring", "painting", "trim_millwork", "windows_doors"],
};
